### ISSUE TITLE
Notes: Delete notes in `GP_Original::delete()` when deleting an original

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#1001]
https://github.com/GlotPress/GlotPress-WP/blob/8adf71b4fed2563c7e253715388a6bb505f87902/gp-includes/things/original.php#L519-L524 should happen in the `delete()` method like done in https://github.com/GlotPress/GlotPress-WP/blob/8adf71b4fed2563c7e253715388a6bb505f87902/gp-includes/things/glossary.php#L164-L175

Can we also change `$note_id` to `$note_ids` while we're here?

**Comment by ocean90** [comment]
Actually, that method is passing an ID of an original while it's expecting an ID of a translation?

**Comment by Mte90** [comment]
I am not sure if the pr is enough.

**Comment by ocean90** [comment]
The notes features has been reverted for now, see #1046.
