### ISSUE TITLE
Feature Request - Open link to consistency tool in new tab

### ISSUE THREAD

**Issue by jeroenrotty** [GlotPress/GlotPress-WP#1011]
As the title is pretty straightforward, it would be cool if the contextual link to the consistency tool opens up in a new tab.

**Comment by Mte90** [comment]
The consistency tool is not from GlotPress but from the meta-i18n team in wordpress.org.
YOu should open a ticket in https://meta.trac.wordpress.org/, anyway glotdict (browser extension) implement already :-)

**Comment by jeroenrotty** [comment]
Sorry for the confusion! @Mte90 

I meant the contextual link within GlotPress. See my screenshot.
![Image 2019-05-20 at 12 46 54 PM](https://user-images.githubusercontent.com/7323966/58016239-63220800-7afd-11e9-9324-73db134d06e7.png)

**Comment by Mte90** [comment]
The consistency tool doesn't exist in glotpress, was built for wp.org and is not part of this project.
So you should talk with them about features etc for that portal, GlotPress is a part of their infrastructure and we are not involved with their integration etc.
