### ISSUE TITLE
Add at page consistency next and previous strings buttons

### ISSUE THREAD

**Issue by PavloGor** [GlotPress/GlotPress-WP#1015]
Hi, Glotpress.
Please add at page https://translate.wordpress.org/consistency/ buttons next and previous strings buttons. In glotpress thya calling "Open previous editor" and "Open next editor".
Thanks

**Comment by toolstack** [comment]
The consistency page is part of meta.wordpress.org, not GlotPress.

You should open a meta ticket on Trac for this.
