### ISSUE TITLE
Variants: Don't add suggestion exactly equal to the parent translation

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1018]
Don't make sense to override a parent translation with a variant translation that is exactly the same as its parent.

While translating in a variant, the user should not be able to add a translation that is exactly the same as the translation of the parent locale and should be notified.

**Comment by ocean90** [comment]
Closing since the feature was reverted in #1327. See also https://github.com/GlotPress/GlotPress-WP/discussions/1333.
