### ISSUE TITLE
Glossary import reference link no longer valid

### ISSUE THREAD

**Issue by ePascalC** [GlotPress/GlotPress-WP#1021]
Importing a glossary from https://translate.wordpress.org/locale/fr-be/default/glossary/-import/ is showing a link to the Google Translator Toolkit, but that has been closed earlier this month.

A link to https://glotpress.blog/the-manual/glossaries/ was suggested in https://meta.trac.wordpress.org/ticket/4905 , but it needs some content first of course, something that explains the header:

en,fr-be,pos,description
"Add new",Ajouter,verb,
Dashboard,"Tableau de bord",noun,"tableau prend une majuscule."

**Comment by toolstack** [comment]
I've created content for https://glotpress.blog/the-manual/glossaries/ that includes the CSV file format.
