### ISSUE TITLE
Create intermediate release, version 2.4

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#1034]
Current stable release is [2.3.1](https://github.com/GlotPress/GlotPress-WP/releases/tag/2.3.1), upcoming release is [planned as 3.0](https://github.com/GlotPress/GlotPress-WP/milestone/8) but due to large changes that require more testing and decisions it's not quite ready yet.

There are currently over [400 commits ](https://github.com/GlotPress/GlotPress-WP/compare/2.3.1...develop) since the latest release. A few of them are regular bug fixes which should have been released much earlier. To fix this I'm volunteering some of my time to prepare an intermediate release which only contains bug fixes, new locales and everything that needs to make the release stable enough to be released (build tools, tests, compatibility with current WordPress version, etc.).
This should also make updating from 2.x to 3.x easier since there will be less changes between those two branches.

**List of changes that should be backported**

* [ ] #869: prepare_original() mangles HTML tags if glossary entry for & exists 
* [ ] #648: Not possible to submit a translation containing the UTF-8 characters → and ↵
* [ ] tbc

----

If you are interested in helping with this release please let me know. The list is still incomplete but if you find something on https://github.com/GlotPress/GlotPress-WP/milestone/8?closed=1 that's not listed yet feel free to mention it in the comments.

**Comment by xavivars** [comment]
Thanks for looking at this!

Also, it would be awesome if release 3.0 could be actually released at some time. I'll try to find some hours these next few weeks.

Having 3.0 in wp.org (with all the variants work there) is something I'm really looking forward, and I know it'll take some time from 3.0 release date until that happens, so the earlier the better.

**Comment by ocean90** [comment]
Closing as wontfix due to the current used [merge strategy](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges) which makes this impossible without having conflict on every second commit. Would have been much easier if all PR commits were squashed into a single commit.

**Comment by pedro-mendonca** [comment]
Hi @ocean90,
I know this issue is closed, but I would like to help with whatever I can.

> If you are interested in helping with this release please let me know.

Would you like help dealing with WPCS issues?

**Comment by ocean90** [comment]
@pedro-mendonca See #585 if you want to help with fixing coding standard issues.

**Comment by pedro-mendonca** [comment]
Can I add this to composer?
```
"require-dev": {
  "dealerdirect/phpcodesniffer-composer-installer": "^0.6.0",
  "wp-coding-standards/wpcs": "^2.2.0",
  "phpcompatibility/phpcompatibility-wp": "^2.1.0"
},
```

**Comment by pedro-mendonca** [comment]
Also, there are a few sniffs that could be fixed on the same PR.
Example:
`WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceBeforeArrayCloser`
`WordPress.Arrays.ArrayDeclarationSpacing.NoSpaceAfterArrayOpener`

Should it be kept in a PR each or could be commited together?

I've tested it in #1059
