### ISSUE TITLE
Separate GP_Format_PO and GP_Format_MO in a file each

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1087]
As mentioned in https://github.com/GlotPress/GlotPress-WP/issues/585#issuecomment-612798333 , `Generic.Files.OneObjectStructurePerFile` should be done at last and require discussion.

These two classes and the file name are pretty straight forward.

Classes file:
`format-pomo.php`.

Classes included:
`GP_Format_PO`
`GP_Format_MO extends GP_Format_PO`

Both classes are required from [`gp-settings.php`](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-settings.php#L114):
`require_once GP_PATH . GP_INC . 'formats/format-pomo.php';`

@ocean90 may I separate it in two files like this?
`require_once GP_PATH . GP_INC . 'formats/format-po.php';`
`require_once GP_PATH . GP_INC . 'formats/format-mo.php';`

**Comment by ocean90** [comment]
Related: #571 and [file naming conventions for classes ](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions)

**Comment by pedro-mendonca** [comment]
All the formats files are consistently in format-XXX.php naming.
The format-pomo.php is the only that has 2 classes (PO and MO).
Despite any further discussion on file naming and autoloading, these could be easily splitted to follow the pattern of the rest of the format classes.
I'll send a PR with the suggestion.

**Comment by ocean90** [comment]
I'd like to avoid renaming the files too often. Since there's no benefit in splitting/renaming them now this can wait.

**Comment by pedro-mendonca** [comment]
Sure 👍 
Feel free to close this.

**Comment by amieiro** [comment]
@pedro-mendonca as the PR related with this issue has been closed, is it ok if I close this issue?

**Comment by pedro-mendonca** [comment]
Sure, close it.
