### ISSUE TITLE
Glossary tooltip not showing for some words

### ISSUE THREAD

**Issue by lidialab** [GlotPress/GlotPress-WP#1169]
Italian Polyglots are observing some missing tooltip from our Italian glossary in translate.wordpress.org platform.

At a first check it seems a problem of expression composed by more words and for words with "-" in them.

Some examples:

"accent" is ok, 
but "accent color" is not ok 
string example: https://translate.wordpress.org/projects/wp-themes/atomic-blocks/it/default/?filters[status]=either&filters[original_id]=6319157&filters[translation_id]=57301288)

"pre-package" is not ok 
string example: https://translate.wordpress.org/projects/wp-themes/zerif-lite/it/default/?filters[status]=either&filters[original_id]=241477&filters[translation_id]=55769101

Thanks, Lidia

**Comment by ocean90** [comment]
The issue seems to have been introduced in #935. The string is now split into parts like "accent" +  "color" so that a term for "accent color" doesn't match anymore. There's also #768 which I think was supposed to block adding new terms with spaces but doesn't appear to work as I'm still able to add "accent color".

cc @toolstack

**Comment by jennydupuy** [comment]
We have the same issue for the locale fr_FR.
It's a pity that expressions with several terms are not taken into account because it avoids the display of warning messages.

**Comment by NekoJonez** [comment]
https://meta.trac.wordpress.org/ticket/5956 in nl_BE & nl_NL, this is also becoming an issue.

**Comment by pedro-mendonca** [comment]
@ocean90 is the PR #1359 still on time for [3.0 milestone](https://github.com/GlotPress/GlotPress-WP/milestone/8)?
