### ISSUE TITLE
Remove locales/no-variants/locales.php

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#1173]
Since there's no easy way to ensure that both locale files are in sync I'm suggesting to simply remove the no-variants file.

If someone doesn't want the variants feature they can either filter the locales through `gp_locale_definitions_arrary ` or create their own copy.

**Comment by pedro-mendonca** [comment]
Is it a typo on `gp_locale_definitions_arrary`?

~`..._arrary`~ -> `..._array`
