### ISSUE TITLE
Glossary - Italian plurals forms are not recognized

### ISSUE THREAD

**Issue by lidialab** [GlotPress/GlotPress-WP#1177]
Hi,
it seems that Italian plurals forms are not recognized in glossary's tooltips.

Example:
in
https://translate.wordpress.org/projects/wp-themes/blossom-coach/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6174160&filters%5Btranslation_id%5D=73326294

"articoli" is the plural form for "articoli" but appears the warning: "Warning: The translation does not contain any of the suggested translations ("pubblicare", "articolo") for the term "Posts"

**Comment by lidialab** [comment]
I'm not sure if it's related to https://github.com/GlotPress/GlotPress-WP/issues/1101
Thanks.

**Comment by ocean90** [comment]
The warning you're getting there is not part of GlotPress. It looks like you're using GlotDict, see https://github.com/Mte90/GlotDict/issues/60.

**Comment by lidialab** [comment]
You're right!
Sorry for annoyance.
Thanks, Lidia
