### ISSUE TITLE
Change status 'Current' to 'Translated'

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1179]
Since https://github.com/GlotPress/GlotPress-WP/pull/1121 there is the 'Translated' link filter.

It corresponds to 'Current only' in the advanced filter.

For consistency, I suggest renaming the all the 'Current' status to 'Translated'.
This includes the status of the string, the import status select, and some of the advanced filters.

**Advanced filter**
![imagem](https://user-images.githubusercontent.com/7371591/85340249-ad826f00-b4dd-11ea-8238-dd82056ed4e8.png)

**String meta**
![imagem](https://user-images.githubusercontent.com/7371591/85340417-f9cdaf00-b4dd-11ea-94d3-527eb1611f5e.png)

**Table bottom**
![imagem](https://user-images.githubusercontent.com/7371591/85340525-2a154d80-b4de-11ea-891e-d67bf948cc8e.png)

**Import screen**
![imagem](https://user-images.githubusercontent.com/7371591/85340346-d9055980-b4dd-11ea-88df-0b68c5c335a6.png)

**Comment by ocean90** [comment]
Going to close this as wontfix because the correct status for an approved translation is current. An original with a waiting translation is also translated but not yet approved.

We could change the link to say "Current" too but I don't think it's necessary.

**Comment by pedro-mendonca** [comment]
Thank you for your feedback.
