### ISSUE TITLE
change request for process that checks the translations and mark them as fuzzy

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1193]
Currently a process is running that checks translations for the locales. This process uses criteria obviously to mark a translation as fuzzy. For a translatior it is sometimes very difficult to underdstand why the string is fuzzy.
Therefore I would like to propose an improvement in this process.
When a record is marked as fuzzy add the reason into the translation. Then a translator knows what to change if a change is needed.

**Comment by ocean90** [comment]
Duplicate of #427.
