### ISSUE TITLE
Glossary Entry import doesn't validate part_of_speech

### ISSUE THREAD

**Issue by dd32** [GlotPress/GlotPress-WP#1200]
It seems like the Glossary Import doesn't validate the value of the `part_of_speech` field, which can be problematic for two reasons:
 - It doesn't display the "custom" value on the glossary page
 - It causes PHP Notices in gp-templates/glossary-entry-row.php

For example, see the month entry on https://translate.wordpress.org/locale/fa/default/glossary/

I see two options here
 - Reject entries which don't match a known value
 - Display the value as-is

It looks like the mismatched values on WordPress.org can be translated, typos, and combinations (ie. `adj, subst`). Abbreviation was common enough that I've created #1199 for that.

**Comment by dd32** [comment]
Example notice:
```
PHP Notice: Undefined index: abbreviation   wp-content/plugins/glotpress/gp-templates/glossary-entry-row.php:4
```

**Comment by ocean90** [comment]
Yeah, we should reject any unknown value.
