### ISSUE TITLE
Fuzzy translation can use some improvements

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/GlotPress-WP#1222]
So, when somebody suggests an update for a fuzzy string... It remains in the fuzzy list. So, that means that possibly 2 or more people suggest a fix for the fuzzy string OR that a fixed version of the fuzzy string is already suggested which can cause confusion and maybe time loss... 

Maybe have something in the lines of "Post-Fuzzy"...? Thinking out loud here. 

Another suggestion on the Slack from @tobifjellner : "I believe the strings should not be removed from Fuzzy, though, since for a GTE that may be the most convenient way to hopefully see what's changed in the source string. But perhaps a flag that someone has already suggested a waiting string for it."

**Comment by ocean90** [comment]
Related/Duplicate: https://github.com/GlotPress/GlotPress-WP/issues/621
