### ISSUE TITLE
You are able to import empty strings (plural/singular issue)

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/GlotPress-WP#1253]
I'm helping @vlad-timotei test his toolset to expand GlotPress and I found this issue: https://github.com/vlad-timotei/wpgp-tools/issues/17

I'm reporting it here as well aka up-stream, since @vlad-timotei is right, you shouldn't be able to import sin/plu strings where one part is empty. 
I THINK how this happend is that when this string got changed into a singular/plural one, it didn't get fuzzied and stayed accepted.

**Comment by ocean90** [comment]
Thanks, we're already tracking this issue in #1191.
