### ISSUE TITLE
[WordPress] Unable to edit some years old translations directly as a validator and delays

### ISSUE THREAD

**Issue by Aikatsui** [GlotPress/GlotPress-WP#1261]
**How to reproduce**

1. I'm not sure if possible to reproduce that with other languages old translations and i think you should have validator role for reproduce this bug.
2. Go to https://translate.wordpress.com/languages/si/default/-all-waiting?ref=weekly-email 
(or [https://translate.wordpress.com/projects/wpcom/themes/twentytwelve/si/_id%5D=5948979](https://translate.wordpress.com/projects/wpcom/themes/twentytwelve/si/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=98903&filters%5Btranslation_id%5D=5948979))
2. Try to change any orange colored string  translation eg: `comment navigation` and tap "add translation". It'll not work **(bug)**

3. Then you need to click "copy from original" button and click "add translation". Wait around 20-25 seconds then it will save source string as the translation. Now add correct translation and click "add translation". Wait around 20-25 seconds then it will save the translation as expected.

Bug - Unable to edit old translations directly as a validator (2)
Problem - Everytime i need to wait around 20-25 seconds for save each translation but no such delay problem with crowdin, weblate, transifex etc platforms

**Comment by Aikatsui** [comment]
Please add this issue to 3.0 milestone and fix soon as possible.
(Why? i don't want to keep them as examples for you without take any action)

**Comment by amieiro** [comment]
Hi @Aikatsui 

This issue is related with the GlotPress installation at wordpress.com, not with the GlotPress plugin. I have talked with the Automattic engineer in charge of this system, and he is working on this issue.
