### ISSUE TITLE
GlotPress interface is not compatible with dark mode

### ISSUE THREAD

**Issue by Aikatsui** [GlotPress/GlotPress-WP#1262]
**Steps to reproduce**

1. Open chromium and go to `chrome://flags/` 
2. Search "Force dark mode for web contents" and enable
3. Go to edit any project on https://translate.wordpress.com
4. See Actions buttons etc contents (Compare with light mode)

![image](https://user-images.githubusercontent.com/63988538/132939699-07114543-9fa6-4689-8241-3daa32c53d16.png)

**Comment by ocean90** [comment]
I'm going to close this as _wontfix_ since there's no plan to support such a forced dark mode setting. We should rather provide a theme which supports a dark mode too.
