### ISSUE TITLE
Glossary should have an option to block an use of a word.

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/GlotPress-WP#1263]
So, in the glossary of nl_BE we have as translation for "Sorry" ... "Geen sorry". 
Which isn't the actual Dutch word for it. But, we have that since we agreed in nl_BE to NOT use "Sorry" in our translations. 

Now, the issue is that... Because of that, it can be confusing to translators and they might translate Sorry always as "Geen sorry". 
Also, it trips up external tools like GlotDict. Which blocks strings because the translation of that word is "missing" while it's supposed to be missing. 

So, it would be handy if we had a way in the glossary if a certain word doesn't need to translated/not be included in the translation like in the above example. So, it's more accessible for translators AND might help external tools like GlotDict to not give warnings since a missing word, that's supposed to be missing, is missing.

**Comment by ocean90** [comment]
The glossary is only intended to provide a tooltip for a term and not to require the use of a word or, in this case, require to not use a word.

Since the tooltip also includes the comment for an entry, you should already be able to make your specific case more clear to translators.
