### ISSUE TITLE
Add JavaScript coding standards

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1280]
Check JavaScript with WordPress Coding Standards and add linting to the workflow

- [x] Add ruleset
- [x] Add scripts and GitHub action
- [x] Fix WPCS
- [x] Replace the obsolete dot files for JSHint with ESLint files.

**Comment by ocean90** [comment]
I think the only thing missing here is updating `.gitattributes` to replace the obsolete dot files for JSHint with ESLint files.

https://github.com/GlotPress/GlotPress-WP/blob/44034fbfcaebbf8d8b31d87812a6f63672fb32ac/.gitattributes#L14-L16
