### ISSUE TITLE
List of all translations of a original on variant shows repeated rows

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1301]
How to reproduce on GP 3 alpha:

- Create root and variant locale translation sets (ex: pt/default and pt-ao90/default)
- Choose an original string and add a few translations on the root
- Also make some some translations on the variant set
- On the variant, go to All Translations for that original

You will now see all the variant translations as expected, but each one of those rows will be multiplied by the ammount of translations on the root locale.

I've checked the db table and it's as expected, the problem is on the translations rows $translations loop.

3x Root translation for a specific original:
![imagem](https://user-images.githubusercontent.com/7371591/144218031-4b4bdd97-6952-4299-a740-4fafc5e741ce.png)

2x Variant translations for the same original, repeated 3x (number of root translations):
![imagem](https://user-images.githubusercontent.com/7371591/144218436-c0e442e2-e340-4a61-9d48-5f287230990d.png)

If I add a new translation to the root set, it will add another row for each of the variant translations.

**Comment by pedro-mendonca** [comment]
Listing all the [$translations](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-templates/translations.php#L393), there are many translations with the same `id`, one per each `root_id`.

Perhaps the $translations array should only include one translation per `id`, being the one related with the 'current' root translation if exist, or most recent root translation.

**Comment by pedro-mendonca** [comment]
This still doesn't solve the filter query count (root_translations * variant_translations), probably it's better to filter the query itself instead of this current solution.

![imagem](https://user-images.githubusercontent.com/7371591/144304458-a5d656f5-0cb1-437b-9c5c-cf7bdb495e76.png)

**Comment by ocean90** [comment]
Closing since the feature was reverted in #1327. See also https://github.com/GlotPress/GlotPress-WP/discussions/1333.
