### ISSUE TITLE
Variant translation set with errors on Fuzzy and Waiting filters

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1303]
The unfiltered variant translation set table shows correctly `current`, `waiting`, `fuzzy` and `warnings` strings.

If filtered by `current`, `untranslated` or `warnings` all works correcly.

The `fuzzy` and `waiting` links have the correct (count) but return zero rows.

**Comment by ocean90** [comment]
Closing since the feature was reverted in #1327. See also https://github.com/GlotPress/GlotPress-WP/discussions/1333.
