### ISSUE TITLE
svn branches/ subdir. Is it needed?

### ISSUE THREAD

**Issue by MocioF** [GlotPress/GlotPress-WP#1362]
Good morning, I am not sure this is the right place to ask (if I am wrong, please just ignore this issue).
Three days ago I committed a new plugin in WordPress.org SVN.
In the developers documentation it is said that a branches directory is unneeded in plugins (just need assets, tags and trunk).
However, no language pack has been created for stable release (tags/1.0.0) but only for development (trunk).
Should I create a branches subdirs and should I populate it in some way to get GlotPress create stable language file?
The plugin is: https://wordpress.org/plugins/no-unsafe-inline/

**Comment by pedro-mendonca** [comment]
Hi @MocioF 
This repo is for the development of the GlotPress tool itself, not the wp.org implementation of GlotPress.
You should use the WordPress Slack #Polyglots channel [as you did](https://wordpress.slack.com/archives/C02RP50LK/p1648363814841569).

**Comment by ocean90** [comment]
I did answer on Slack.

> Usually you can fix this by yourself by doing a whitespace change to one of the files in the stable tag directory. This will trigger another import.
I have now forced a new import and the stable project does now exist.
