### ISSUE TITLE
GlotPress not correctly localized

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1365]
The GlotPress UI translation is only loaded if `site_language` is customized to a non `en_US`.
If `site_language` is `en_US` and `user_language` is customized, GlotPress UI keeps `en_US`.

For sites in `en_US`, the users should be able to set their admin UI in any supported language.

This behavior applies to current stable v.2.3.1 and beta v.3.0.0.

**Comment by ocean90** [comment]
Are you saying that the user locale should be used on the frontend?

**Comment by pedro-mendonca** [comment]
Being possible to customize the `user_language` for the wp-admin, I think that's what a user expects when customizes it.

Of course this being a translation platform, it's supposed to understand English, but the UI should be translated for a team that wants everything on the UI on its own language, as already works if customize the `site_language`.
Not being able to set it on user level looks just like a bug.

**Comment by ocean90** [comment]
GlotPress itself has no setting to set a locale per user. It relies on what core does and `get_user_locale()` is currently not intended for use on the frontend as you can see in [`determine_locale()`](https://developer.wordpress.org/reference/functions/determine_locale/). That's also the reason why the admin bar on the frontend is also in the site language.

Closing with the option to reconsider it for later once core has better support for mixed languages on a site.

**Comment by pedro-mendonca** [comment]
I would still like to make a proposal that I'll add as a PR:
The `get_user_locale()` can be hooked in `pre_determine_locale`.

I think it works well, I see no catch, please check it out.

**Comment by pedro-mendonca** [comment]
> GlotPress itself has no setting to set a locale per user.

I think it's correct, GlotPress can and should rely upon the WordPress user settings for that.

I agree that is a hack, but is the expected behaviour.
