### ISSUE TITLE
Glossary errors on non-en_US admin

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1366]
If the install is running on a translated (non-en_US) language, it's not possible to add glossary entries, as the translated `part_of_speech` never match the available array of allowed types.

**Comment by ocean90** [comment]
Seems to be introduced in #1277. 

https://github.com/GlotPress/GlotPress-WP/blob/51d7c3b1275684b3befd2dcc89f6f40ef5c127f8/gp-includes/things/glossary-entry.php#L83

This should be changed to `array_keys( $this->parts_of_speech )`.

**Comment by pedro-mendonca** [comment]
~Yep, that's the problem. Should I add a PR?~
Done!
