### ISSUE TITLE
Add more suffixes for glossary matches

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1372]
Words ending with 'e' could be added some more suffixes.

Example:
`delete` -> `deleted`, `deletion`, `deleting`
`complete` -> `completed`, `completion`, `completing`
etc

**Comment by pedro-mendonca** [comment]
Here is a comprehensive list of -ion suffix rules
https://www.thefreedictionary.com/Commonly-Confused-Suffixes-tion-vs-sion.htm

Adding many rules will increase the glossary matching process, probably we should decide which ones to add or not.

**Comment by ocean90** [comment]
> Adding many rules will increase the glossary matching process, probably we should decide which ones to add or not.

Correct, we should only add suffixes when they make sense. I have already created #1384 and #1386 for the current rules. But there are a few more for which I haven't created issues yet, like for words already ending with `ing`.

So if we can convert the above suffix rules into code that would be great.

**Comment by pedro-mendonca** [comment]
Another good reference about suffixes:
https://www.thefreedictionary.com/Suffixes.htm

**Comment by pedro-mendonca** [comment]
@ocean90 according to the list of suffixes above, we should set a list of desired suffixes and rewrite the rules code to include a check for `part_of_speech`, so there can be used different suffix rules for nouns, verbs, etc.

**Comment by pedro-mendonca** [comment]
In https://github.com/GlotPress/GlotPress/pull/1373/commits/72fffd6fc4c47f08d3e16266ef84a235c82b187e I've made a first approach to implement separate lists of suffixes per term types. 

It's very low performant as I've added too many cases, we can choose to include or exclude easily by commenting out the array items.

Let me know your thoughts please.

**Comment by pedro-mendonca** [comment]
I've added a huge list of matches to the PR #1373.

**Comment by amieiro** [comment]
Fixed in https://github.com/GlotPress/GlotPress/pull/1373.
