### ISSUE TITLE
Links to Glossary

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1374]
The workflow to access the Glossaries need to be clearer.

There are two types of Glossary:
 - Locale Glossary
 - Project Glossary

### Case 1
 - Locale Glossary is set
 - Project Glossary isn't set

On the page Locale page we have a **Locale Glossary** link on top right corner
![imagem](https://user-images.githubusercontent.com/7371591/161066082-0310028f-a71a-4e0d-a318-f8a98c03cf44.png)

On a project/set that has no Project Glossary, on top right we have a link to **Create Glossary**
![imagem](https://user-images.githubusercontent.com/7371591/161066785-22658041-33fa-4d37-9164-5b59a16f0d7f.png)

### Case 2
 - Locale Glossary is set
 - Project Glossary is set

On a project/set that has Project Glossary, on top right we have a link to **Glossary**.
It's not clear wether is the Project Glossary or a Locale Glossary.
![imagem](https://user-images.githubusercontent.com/7371591/161067723-ecd3824f-a2fe-45aa-8f12-73b6b9fabec7.png)

### Suggestion
As a Locale Glossary is set and being used as fallback for the project, would be great to add the link to it.
On each translation set, there could be a link for both Locale and Project glossaries, with its alternative link to Create if doesn't exist.
![imagem](https://user-images.githubusercontent.com/7371591/161072760-e8cdfd4e-3c27-4c34-b95d-d251d44d9d22.png)

**Comment by alvarogois** [comment]
Thanks @pedro-mendonca. I've been dealing myself with this UI flaw over the years. Currently it's not clear at all.

**Comment by fxbenard** [comment]
Good point, and renaming "Glossary" to "Project Glossary" and "Create glossary" to "Create project glossary" might help as well.

**Comment by pedro-mendonca** [comment]
@fxbenard as in my last screenshot :-)

**Comment by pedro-mendonca** [comment]
It would be good also to make it clear on the page title:

## Locale Glossary
![imagem](https://user-images.githubusercontent.com/7371591/161079107-85ed07b3-a31b-4850-9209-c06fec3d91ce.png)

## Project Glossary
![imagem](https://user-images.githubusercontent.com/7371591/161079336-7c639456-a063-4032-9544-f8db614e7a8a.png)

**Comment by pedro-mendonca** [comment]
Some more suggestions about making the existent **Project Glossaries** more visible:

#### Project view - Show all the existent Project Glossaries in the Locales column
![imagem](https://user-images.githubusercontent.com/7371591/161287462-f91395b0-f55d-4f0c-bf94-18f4e9de39f9.png)

#### Locale view - Show all the existent Project Glossaries in the Sub-project column
![imagem](https://user-images.githubusercontent.com/7371591/161288140-c8fab975-4d85-46fb-ae03-91daa0512446.png)

Feedback wanted.

**Comment by fxbenard** [comment]
As I'm not a big fan of project glossaries that bring more errors (cause they usually never get updated) in my opinion before showing it everywhere it will be nice to show in the editor if a glossary term is coming from the locale or project glossary.
But indicating that a project glossary exists is a good point cause it might help to find out why glossary terms aren't right ;)

**Comment by pedro-mendonca** [comment]
Agree. I've never used Project Glossaries either, but existing, it's a good idea to show the term origin, with a link to it.

**Comment by La-Geek** [comment]
As an addition: In German we have two variants (default and formal) and so we have also two glossaries:

https://translate.wordpress.org/locale/de/default/glossary/
https://translate.wordpress.org/locale/de/formal/glossary/

The correct URL, depending on whether default or formal to the appropriate glossary would be great.
