### ISSUE TITLE
Glossary: Don't provide a tooltip for HTML tags

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#1382]
Having an entry for `strong` should not provide a tooltip for `<strong>` tags.

<img width="349" alt="" src="https://user-images.githubusercontent.com/617637/161428428-4f901037-c14a-4bc0-a4b8-4303cb0507d1.png">

This also contradicts the [`notranslate` CSS class](https://github.com/GlotPress/GlotPress-WP/blob/5b4adbb41931dd0cbea5957de9c7514cbc96777e/gp-templates/helper-functions.php#L30):

<img width="880" alt="image" src="https://user-images.githubusercontent.com/617637/161428483-6c6079fd-9739-44b4-a1bf-d9577814c027.png">

**Comment by NekoJonez** [comment]
You could expand that logic into urls too
