### ISSUE TITLE
Glossary: Don't add suffixes to terms already ending with an 's'

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#1384]
```
'notifications|notificationss|notificationses|notificationsed|notificationsing'
'requirements|requirementss|requirementses|requirementsed|requirementsing'
'permissions|permissionss|permissionses|permissionsed|permissionsing'
```

When adding a new glossary entry it's actually not documented what type the term should be. The code currently assumes that only a singular term is added but that's not always the case causing the weird terms from above generated by `gp_sort_glossary_entries_terms()`.

Reducing the number of terms will reduce the risk of running into issues like #1377.

Found the examples in https://translate.wordpress.org/locale/nl-be/default/glossary/.

**Comment by ocean90** [comment]
Words like "dismiss" might be an exception, though, "dismisss" should be avoided:

`'Dismiss|Dismisss|Dismisses|Dismissed|Dismissing'`

**Comment by pedro-mendonca** [comment]
Would it make sense to suggest to only add the nouns in the singular form?
Here are some rules we could use to check the inserted terms and warn in case of plural form inserted:
https://www.thefreedictionary.com/Forming-Plurals.htm

**Comment by pedro-mendonca** [comment]
> When adding a new glossary entry it's actually not documented what type the term should be. The code currently assumes that only a singular term is added but that's not always the case causing the weird terms from above generated by `gp_sort_glossary_entries_terms()`.

As can be seen in the proposed changes to the plural rules in #1373, based on (https://www.thefreedictionary.com/Forming-Plurals.htm, there are many rules according to the ending and what precedes the ending of the words, and many are many-to-one, making it impossible to revert from plural to singular.

Example: Wife (`-fe`) and leaf (`-f`) both have plural suffix `-ves`.

To revert, if found words `wives` and `leaves`, it's not possible to know if `-ves` is to change to `-f` or to `-fe`.
The same impossibility happens on reversing verbs from other tenses to infinitive.

So, I suggest documenting that Nouns should be in Singular and Verbs should be in Infinitive.

Of course, nouns can still be in plural and verbs in other than infinitive, which will produce odd matches, but adding an extra layer of check for that will make everything probably more heavy than just accept the fact that some impossible matches will be searched.

**Comment by pedro-mendonca** [comment]
> Words like "dismiss" might be an exception, though, "dismisss" should be avoided:
> `'Dismiss|Dismisss|Dismisses|Dismissed|Dismissing'`

On #1373 the verb `dismiss` produces **only** the following matches: `dismiss ( es | ed | ing )`

**Comment by amieiro** [comment]
With the PR https://github.com/GlotPress/GlotPress/pull/1373, I have set up these words (notifications, requirements, permissions, dismiss) as nouns in the glossary, and this is the result:

![image](https://github.com/GlotPress/GlotPress/assets/1667814/4576b057-bffa-4cb1-b654-f469da50beac)

If I set these four words as verbs, this is the result:

![image](https://github.com/GlotPress/GlotPress/assets/1667814/533a0e37-4da7-4dde-8bc1-1f52a2f7945c)

This PR reduces the amount of matches in both situations, but after merging it, we can try to determine some special situations in the glossary words, avoiding to calculate more variations:
- Nouns. Determine if the word is plural, following the pluralization rules and the nouns ending in "-tions" (e.g., authorizations) or "-sions" (e.g. supervisions), made using a verb.
- Verbs. Determine if it is some special type: Third-person singular, past (-ed), gerund (-ing).

**Comment by pedro-mendonca** [comment]
I think one of the premises and best practice of the Glossary usage is adding nouns in singular, and verbs in the infinitive. Adding nouns in plurals and verbs in any other verbal form introduces unnecessary logic to the suffix matching.
