### ISSUE TITLE
Glossary: Don't provide a tooltip for strings in CSS class names

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#1385]
Similar to #1382 but for HTML attributes like `class`.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/617637/161431305-5357a854-a3bc-4c42-b146-ecae7762b716.png">

**Comment by amieiro** [comment]
This issue is resolved in the https://github.com/GlotPress/GlotPress/pull/1679 PR, that solves the https://github.com/GlotPress/GlotPress/issues/1382 issue.

**Comment by amieiro** [comment]
Close this issue, because it has been resolved at https://github.com/GlotPress/GlotPress/pull/1679.
