### ISSUE TITLE
text-underline-offset, text-decoration-thickness and readability

### ISSUE THREAD

**Issue by webaxones** [GlotPress/GlotPress-WP#1387]
Hi,
I think changing the text-underline-offset for both .glossary-word and .gp-content a, li>a, p a was a mistake.
Why? 
Because we end up with the final horizontal bar of g j y hidden by the underline instead of the latter crossing the vertical bar.
And it's much less readable.

Now:
![image](https://user-images.githubusercontent.com/17084006/161559065-2e0a581b-ca19-4b50-a65e-2e852fe38549.png)

Instead of:
![image](https://user-images.githubusercontent.com/17084006/161559281-317323f4-b427-428f-93db-eb19053a0c78.png)

Now with zoom:
![image](https://user-images.githubusercontent.com/17084006/161559657-50f3d7bd-c405-440e-a74f-097563a48891.png)

Instead of:
![image](https://user-images.githubusercontent.com/17084006/161559618-2b1dfe6a-6a0b-4602-984e-a8eaa51e3508.png)

So I think you should remove:

```
text-decoration-thickness: max(1px,0.063rem);
text-underline-offset: 0.1em;
```
for 
`.glossary-word`
and 
```
.gp-content a,
li>a,
p a
```

:)

**Comment by ocean90** [comment]
It looks like you're actually referring to some selectors used on translate.wordpress.org. But GlotPress provides the same styling in https://github.com/GlotPress/GlotPress-WP/blob/5b4adbb41931dd0cbea5957de9c7514cbc96777e/assets/css/style.css#L126-L142.

We can probably improve this by using `text-underline-position: under;`.

**Comment by webaxones** [comment]
Sorry I got tricked regarding the origin of the code :( 
I fear that `text-underline-position: under` multiplied by a number of lines on a translation page will greatly increase the height of the page and so the needed scroll.
Translations could have the same underline height than on https://wordpress.org. More readable by default :)

**Comment by ocean90** [comment]
No,`text-underline` doesn't increase the height of a page.

**Comment by webaxones** [comment]
That's true. But more space is used. In fact I don't know what to think of this solution, it may be good. Anyway, thank you for considering the issue :)
