### ISSUE TITLE
When using a mobile the labels are not shown properly

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1389]
If a translation contains a label which is long, it is not wrapped on a mobile. It is not contained within the original, but is shown over both columns original and translation. If the translated text is longer then the orinal, the label is shown through the translation

**Comment by ocean90** [comment]
Can you please provide some screenshots and details about your mobile device?

**Comment by psmits1567** [comment]
Unfortunately my screenshot app is not shown when you start translating from the slack link
I am using a Nokia * phone with android latest version.
But there is no need to see the screenshot from the mobile, as the behavior is the same, when you resize your screen on your desktop. Then you see the same effect happening, the label is static not dynamic
![Knipsel](https://user-images.githubusercontent.com/28138634/161717047-20f568ba-b319-4d87-83af-0dbb7388be02.JPG)

**Comment by psmits1567** [comment]
Finally managed to get a screenshot from my mobile.
I noticed that currently when translating normal projects this label is wrapped
But when I look into the APP ->Android I see the below results
![Screenshot_2022-04-05_161356](https://user-images.githubusercontent.com/28138634/161777948-2036e4ae-7522-4bb9-bc96-1974eb76e9aa.jpg)

**Comment by ocean90** [comment]
Looks like this only happens on https://translate.wordpress.org/projects/apps/android/dev/es/default/. I'll see if it can be fixed there.

Marking as invalid since it's not in issue with the default GlotPress plugin.

**Comment by psmits1567** [comment]
OK strange that there are two different systems to present the data
