### ISSUE TITLE
Don't include default priority as flag in exports

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#1390]
#1341 added the `gp-priority` flag also to PO/POT exports which makes the files a bit too verbose now as most if not all of the entries will get the `gp-priority: normal` comment. Since `normal` is the default priority I don't think we have to export it.

Example: https://i18n.trac.wordpress.org/changeset/825545

@dd32 Do you have any objections?

**Comment by dd32** [comment]
I'm not sure it's an actual problem, as manual editing of the files is pretty rare.

That being said, I have zero objections to skipping it for `normal`.
