### ISSUE TITLE
Edge case? Placeholders & glossary words.

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/GlotPress-WP#1400]
https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/dev/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9836002&filters%5Btranslation_id%5D=93348563

In nl_BE, we have an entry for "Show" in our glossary. In the above string, we have a placeholder that ends on "s" and the rest of the string continues with "how"...

Somehow, GlotPress sees this as a glossary word while it shouldn't.

**Comment by ocean90** [comment]
Copying the HTML markup in case the string gets lost:

```html
The <span class='glossary-word' data-translations='[{"translation":"links","pos":"noun","comment":","locale_entry":"}]'>links</span> columns <span class='glossary-word' data-translations='[{"translation":"tonen","pos":"verb","comment":","locale_entry":"}]'>show</span> the number of articles on this <span class='glossary-word' data-translations='[{"translation":"website","pos":"noun","comment":","locale_entry":"}]'>site</span> linking <span class='notranslate'>%3$s</span>to<span class='notranslate'>%4$s</span> this article and the number of URLs linked <span class='notranslate'>%3$s</span>from<span class='notranslate'>%4$s</span> this article. Learn more about %1$<span class='glossary-word' data-translations='[{"translation":"tonen","pos":"verb","comment":","locale_entry":"}]'>show</span> to use these features to improve your internal linking<span class='notranslate'>%2$s</span>, which greatly enhances your SEO.
```

<img width="353" alt="image" src="https://user-images.githubusercontent.com/617637/162751012-7e83ee00-7076-47c2-9887-9bb714a404bf.png">

**Comment by NekoJonez** [comment]
@ocean90  I dare to argue that this might get the documentation label as well. Since, correct me if I'm wrong but I dont find any documentation on how this html is written and how we can implement that. While I know how, I think... Its better to have documentation... Or make a seperate ticket for that?
