### ISSUE TITLE
Readme texts

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1405]
The string `So who should use GlotPress?` and its answer appears twice, inside and outside the FAQs.
It might be removed so it appears only within the FAQ.
Currently the answers differ in a single double space that adds two strings to the translation table, can be fixed quickly.

I think the below string isn't quite up to date already
`GlotPress has two versions, a standalone version and this WordPress plugin version. At this time these two versions are functionally similar, but the plugin version is likely to start moving away from the standalone version in future versions. For the rest of this document, any reference to "GlotPress" should be taken as the plugin.`
To start, mentioning the standalone GlotPress as a present option. Second, they're probably not similar in functionality anymore.

To close, there are some `http://` links that can be set to `https://`.

**Comment by ocean90** [comment]
I'm fine with removing any mention of the standalone version in the readme.

**Comment by pedro-mendonca** [comment]
What about the duplicate `So who should use GlotPress?` ? Should be kept as is, or use only once, on the FAQ?


About removing any mention to the standalone version, wouldn't be nice to keep the thanks message (`This plugin wouldn't be possible without...`) ?

**Comment by ocean90** [comment]
I think we can remove the FAQ section completely. None of these are frequently asked and already included in the description. The thank you line can stay of course.

**Comment by pedro-mendonca** [comment]
Thanks for the feedback.
All done in #1406 and #1407
