### ISSUE TITLE
Add a column showing the date when an entry has been added to the glossary

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1423]
Currently there is no way to see when a new entry has been added to the glossary. To check if a new entry has been added recently it would be great if a column is added to the glossary list showing the date when an entry was added. Then you can see quickly if the glossary has had a change.

**Comment by pedro-mendonca** [comment]
A good addition to this would be table sorting.

**Comment by ocean90** [comment]
I'd go with one column named "Last modified". That covers the case when you want to check if anything was recently changed, either added or updated. Moved to 4.0 milestone as it fits into the release focus.
