### ISSUE TITLE
Glossary: Add sorting to the table

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1425]
Add tablesorter to the glossary table to quickly sort by any column.

**Comment by ocean90** [comment]
For the start I'd keep it simple and only allow to sort the Item, Translation and the Last Modified column when added in #1423.

Moved to 4.0 milestone as it fits into the release focus.

**Comment by pedro-mendonca** [comment]
I agree on leaving Comments out, but not so sure about Part of Speech.

**Comment by ocean90** [comment]
To me Part of Speech is more a categorization like "show me all nouns", not something I'd sort the results on. But I guess it doesn't really matter since for tablesorter is also just text to sort.

**Comment by pedro-mendonca** [comment]
You're right.
I've finished #1426 with sorting only for Items and Translations.
