### ISSUE TITLE
Allow validators to add notes to original strings

### ISSUE THREAD

**Issue by nielslange** [GlotPress/GlotPress-WP#1440]
While working on translations for the WooCommerce plugin, I noticed various mistakes in an original string.

- [Link in Trac](https://plugins.trac.wordpress.org/browser/woocommerce/trunk/src/Database/Migrations/CustomOrderTable/CLIRunner.php#L438)
- [Link on WordPress.org](https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/de/default/?filters%5Boriginal_id%5D=13834180)

### Original code

```php
_n(
   '%1$d order was verified, in %2$f seconds. %3$f error(s) found: %4$s',
   '%1$d orders were verified in %2$f seconds Please review above errros. %3$d error(s) found %4$s. Please review above errors.',
   $processed,
   'woocommerce'
)
```

### Problems

1. The singular string contains a comma between `verified` and `in %2$f seconds`. The plural string does not contain this comma.
2. The plural string does not contain a full stop between `in %2$f seconds` and `Please`.
3. The plural string contains `Please review above errors.` twice, while the singular string does not have that entry.
4. One of the duplicated messages, that I mentioned in 3., says `Please review above errros.` instead of `Please review above errors.`

#### Simple option

Only correct the current mistakes:

```php
_n(
   '%1$d order was verified in %2$f seconds. %3$f error(s) found: %4$s. Please review above errros. ',
   '%1$d orders were verified in %2$f seconds. %3$d error(s) found %4$s. Please review above errors.',
   $processed,
   'woocommerce'
)
```

#### Advanced option

Splitting the translations in two parts to utilize `_n()` correctly:

```php
_n(
   '%1$d order was verified in %2$f seconds. ',
   '%1$d orders were verified in %2$f seconds.',
   $processed,
   'woocommerce'
)
```

```php
_n(
   '%1$f error found: %2$s. Please review the error above. ',
   '%1$d errors found %2$s. Please review the errors above.',
   count( $failed_ids ),
   'woocommerce'
)

```

### Expected solution

While I've already reached out to the author of this code section, as a PTE, it would be nice to leave a note on the original string. This way, I could inform others that this string should be corrected before it can be translated.

Given that this example affects all languages, it would be nice if a PTE has the ability to choose between adding the note to a single locale or as a general note, so that it shows for all locales. 

I also think that it would be nice to be able to be able to use code blocks in the notes, so that a better approach could be suggested directly.

**Comment by pedro-mendonca** [comment]
Hi @nielslange,
Welcome to the repo!

Feedback for the code authors would be amazing.
Currently, there is a feature plugin being developed for adding discussions and feedback to GlotPress, that is intended to be merged into GlotPress in the future.

I suggest you drop by https://github.com/GlotPress/gp-translation-helpers and add this feedback suggestion to it.

**Comment by amieiro** [comment]
Hi @nielslange 

As Pedro said, we developed a new plugin ([gp-translation-helpers](https://github.com/GlotPress/gp-translation-helpers)) to send a message to the administrators with information like this. You can:
- Notify some typo in the original text.
- Request more context about the original string.

![image](https://github.com/GlotPress/GlotPress/assets/1667814/aa1ab577-3b6c-4977-8695-24fcd7a7c097)

At [translate.w.org](https://translate.wordpress.org/) we have this plugin with an improvement, sending this comments to one of the developers, if they have opt-in to receive notifications (by default, all users are opt-out).

![image](https://github.com/GlotPress/GlotPress/assets/1667814/6aed4465-6b90-417c-a3a9-ef76b79ff558)

I close this issue, as this improvement solves this problem. Feel free to open it another time if you have something to comment.

**Comment by nielslange** [comment]
Hello @pedro-mendonca and @amieiro 👋

Thanks for your replies and great to see that this feature has been implemented. 

@pedro-mendonca Sorry for not responding earlier. I missed your initial message. 🙈
