### ISSUE TITLE
Non-editor role contributor can't re-suggest self-rejected translation

### ISSUE THREAD

**Issue by naokomc** [GlotPress/GlotPress-WP#1462]
Here's a scenario. 

1. A translator who doesn't have an editor role enters a translation.
2. She thinks there's a mistake, and rejects her own translation.
3. She changes her mind and wants to suggest the same translation.
4. There isn't a way for her to do this, because she'll get an "`Error: Identical rejected translation already exists.`" message if she tries to enter the same translation. Also, there is no way for modifying the status of the translation.

Tested on here:
https://translate.wordpress.org/projects/wp/dev/pirate/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=3062038&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc

## Suggestion

How about overriding the status of the old translation when an identical translation is suggested by the same person?

Or add a "Suggest" button to rejected translations?
<img width="1201" alt="スクリーンショット 2022-06-29 15 44 36" src="https://user-images.githubusercontent.com/34067/176370268-3f307f86-959b-42c5-96bf-c02b3156614d.png">

**Comment by ocean90** [comment]
This seems to be an issue specific to translate.w.org and not GlotPress itself.
The change was added in https://meta.trac.wordpress.org/changeset/10575 and is slightly related to https://meta.trac.wordpress.org/ticket/5576.

**Comment by naokomc** [comment]
I see, thank you! I left a comment in the ticket, this can be closed now.
