### ISSUE TITLE
Show the number of characters in translation

### ISSUE THREAD

**Issue by amieiro** [GlotPress/GlotPress-WP#1474]
As @tobifjellner suggests [here](https://wordpress.slack.com/archives/C02RP50LK/p1660119378388429), it would be interesting to add the number of characters in the translation, in the bottom right corner.

**Comment by pedro-mendonca** [comment]
What about both characters and words?

![imagem](https://user-images.githubusercontent.com/7371591/186178663-b1358250-e69a-48e9-a33d-c933cbe66cbd.png)

**Comment by pedro-mendonca** [comment]
With counts both on the orignal and translation:

![imagem](https://user-images.githubusercontent.com/7371591/186419103-05745613-c146-4fe9-9da3-3db39663be9b.png)
