### ISSUE TITLE
Show date of last language pack

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/GlotPress-WP#1483]
I don't know if this is something for here OR for Meta trac ... But, I think it would be handy if on the project page a date is displayed when the last language pack was created. That would make it easier to know if e.g. a project dips below 90% translation if corrections went through to the users amongst other things.

**Comment by pedro-mendonca** [comment]
GlotPress actually doesn't provide Language Packs. For w.org, that is some [customization code](https://github.com/WordPress/wordpress.org/blob/3bcdf0e4083a3d7d0ffaaecd129b04e41955f6a4/wordpress.org/public_html/wp-content/plugins/wporg-gp-customizations/inc/cli/class-language-pack.php) on meta-i18n.

**Comment by NekoJonez** [comment]
I'll close this ticket then and open one on Meta trac :)
