### ISSUE TITLE
Add validation to strings that are mere settings not to translate

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1484]
Some projects use translation strings as simple settings, that should be filled with one of a set of options.

Examples on WordPress core: [ltr](https://translate.wordpress.org/projects/wp/dev/pt/default/?filters[original_id]=40305), [word count type](https://translate.wordpress.org/projects/wp/dev/pt/default/?filters[original_id]=533157), [Open Sans font](https://translate.wordpress.org/projects/wp/dev/pt/default/?filters[original_id]=76554), [Google Font Name and Variants](https://translate.wordpress.org/projects/wp/dev/pt/default/?filters[original_id]=6929622), etc.

There could be added some proper soft validation, as currently exists for when some variable is missing.

To inform GlorPress that a string is a setting, there could be used a particular string context like `no-translate-setting`, and maybe some finite comma separated set of options through the `/* translators: Comment. */`

Example:
```
/* translators: Settings: rtl,ltr. This sets the text direction for WordPress. */
_x( 'ltr', 'no-translate-setting', 'textdomain' );
```

With this, GlotPress could easily check for a comma separated list of options in case it's a `no-translate-setting` and show a soft warning when the translation isn't one of the predefined options.

The naming of this convention is just an idea, could be better.

**Comment by Zodiac1978** [comment]
I love this idea!

But I have questions how to achieve the implementation. I am not much deep in PHP, like many others, but I think we need a different function than `_x`.

Using a fixed `context` collides with all the "on/off" strings, which need different contexts to separate them.

Using a callback function as a fourth parameter will not work, because the text-domain is optional and therefore will lead to unwanted results if the text domain is omitted. Changing the order will also be a breaking change.

As a mediocre PHP programmer, I can just think of a new i18n function to solve this.

Any better ideas? Would love to see a fix for this, because there are many settings in WordPress core.

Not sure if I have found all, but here I started a list:
https://gist.github.com/Zodiac1978/1d1bd363d5ba7d1ea68e3ffe352008f1

**Comment by Zodiac1978** [comment]
@ocean90 How is the best way to start a discussion about this? Opening a core trac ticket?

**Comment by pedro-mendonca** [comment]
> Using a fixed context collides with all the "on/off" strings, which need different contexts to separate them.

You're right. Maybe some convention on that also. Different contexts, but with a common part that could easily be filterable and searched.

About a new gettext wrapper, is it possible to keep the support for older WP versions to use GlotPress?

**Comment by NekoJonez** [comment]
So, as I said on Slack... I personally would love to see this work with the warning system. Why not block translators from inputting something wrong and only warn? Well, imagne that a dev refactors or reorganizes code and a certain comment stays where it shouldnt... That way we make it difficult for us translators. Thats one example I can come up with.

**Comment by pedro-mendonca** [comment]
If a comment changes it doesn't raise any issues with the current translation, and in fact it can be kept translated until someone stumbles on it.
But, if the context changes, it's considered a new string, and might a better approach. I see no problem to use context instead of comment for translators. I've seen complete descriptive sentences in string contexts, it's all ok.
Something like `Setting: [ltr,rtl]` as a context would be easily parsed by GlotPress and used as the only valid options.
A generic short array syntax is very easy to use for it, with a prefix `Setting:` or `Options: `, or any other convention, that could be defined per install.

**Comment by Zodiac1978** [comment]
At least for WP.org there is a solution worked on:
https://github.com/WordPress/wordpress.org/pull/150

**Comment by amieiro** [comment]
A solution has been implemented and released in:
- GlotPress. https://github.com/GlotPress/GlotPress/pull/1644
- translate.w.org. https://github.com/WordPress/wordpress.org/pull/162

I close this PR. Feel free to open it if you want to discuss anything about this.
