### ISSUE TITLE
Specify added/removed spaces on warnings

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#1489]
Use `_n()` to specify both added and removed spaces on warnings about different spacing at the beginning or ending of translation strings.

Current:

`The translation appears to be adding one or more spaces at the beginning.`
`The translation appears to be adding one or more spaces at the end.`
`The translation appears to be missing one or more spaces at the beginning.`
`The translation appears to be missing one or more spaces at the end.`

Suggestion:

![imagem](https://user-images.githubusercontent.com/7371591/191304332-7c640417-c3b8-4f86-9890-19fa0bfbfc86.png)
![imagem](https://user-images.githubusercontent.com/7371591/191304415-2c00c8b2-3aac-4675-94dd-fd1df8b3aaed.png)
![imagem](https://user-images.githubusercontent.com/7371591/191304623-32451d84-6e3f-46c6-adf2-515a5bcbe0e4.png)

Related to https://github.com/GlotPress/GlotPress/pull/1427

**Comment by NekoJonez** [comment]
Speaking about the spaces at the end and such... In WPGP by @vlad-timotei, it also shows that. It also gives you a warning for double spaces. But, that's something we in nl_NL/nl_BE ignore because grammar... So, maybe add a feature to ignore double spaces and make it fine for one space?
