### ISSUE TITLE
Setting the status to "changesrequested" - Missing space?

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/GlotPress-WP#1495]
In the yellow pop-up when setting a string to "changes requested", it's missing a space.

![image](https://user-images.githubusercontent.com/4569581/192483640-79961b99-e124-49dd-8694-4ab206eee763.png)

Shouldn't there be a space between changes & requested?

**Comment by trymebytes** [comment]
This has been fixed in #1369 , I'll be closing this issue.
