### ISSUE TITLE
Add "Untranslated" as a reject with feedback reason

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/GlotPress-WP#1501]
Quite often I see that people give suggestions that aren't fully translated or just untranslated. I think this is a nice option in the list of standard reject with feedback options.

**Comment by amieiro** [comment]
I am going to close this issue, as currently is related with the [gp-translation-helpers](https://github.com/GlotPress/gp-translation-helpers), not with GlotPress. I have copied this issue into the [gp-translation-helpers issues](https://github.com/GlotPress/gp-translation-helpers/issues/127).
