### ISSUE TITLE
Dutch Formal isn't in the default locale list

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/GlotPress-WP#1507]
The nl_NL-formal, which we have in translate.wp.org isn't an option in the default locale list.

**Comment by amieiro** [comment]
The languages at translate.wordpress.org has variations. The default one is "default". You can see it in the URL https://translate.wordpress.org/locale/es/default/wp/dev/

![image](https://user-images.githubusercontent.com/1667814/196156880-4fbb8b1f-7961-4dff-b1e6-a76d5f9bc0bc.png)

In the Dutch situation (nl_NL), we have:
- The default (informal): https://translate.wordpress.org/locale/nl/default/wp/dev/
- The formal variation: https://translate.wordpress.org/locale/nl/formal/wp/dev/
![image](https://user-images.githubusercontent.com/1667814/196156487-a5d375d0-d803-4c72-aa2b-db87f3c103a8.png)

These variations are related with translate.wordpress.org environment, not with GlotPress.

**Comment by ocean90** [comment]
To extend what @amieiro has already said:

* w.org has a custom locales file which you can view [here](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php).
* For the variants w.org uses different slugs for the translation sets which then can be mapped to a default or custom locale.
* To replicate the same behaviour in a custom install you'd have to expand the locales list with either a custom file like w.org does or by using the [`gp_locale_definitions_array` filter](https://github.com/GlotPress/GlotPress/blob/f6c286c293110daed1494da2d18ea9133c939e83/locales/locales.php#L2801) which might be easier.
