### ISSUE TITLE
Error messages not fully translate-able

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/GlotPress-WP#1508]
I fully translated GlotPress in my locale and I noticed that "Error:" can't be translated. Example here:

![image](https://user-images.githubusercontent.com/4569581/196144848-d41188c9-e0be-474b-afac-dcd7836706d2.png)

(Running the current version in the plugin repo)

**Comment by amieiro** [comment]
Using an online translator, I see this error is "Error: Identical current or waiting translation already exists.", so I think this is the problem: you are trying to use the same translation you have in the system, in current or waiting status. This is the normal operation of GlotPress.

**Comment by ocean90** [comment]
This is a duplicate of #1368.

**Comment by pedro-mendonca** [comment]
The translation of the part "Error:" of the error notice is fixed in https://github.com/GlotPress/GlotPress/pull/1369/.
