### ISSUE TITLE
PHP Errors (6 Deprecated)

### ISSUE THREAD

**Issue by fernandopro** [GlotPress/GlotPress-WP#1518]
- Wordpress : 6.1
- PHP version : 8

**PHP Errors:**
Deprecated || Required parameter $meta_key follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:82
Deprecated | Required parameter $meta_value follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:0
Deprecated | Required parameter $type follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:0
Deprecated | Required parameter $meta_key follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:168
Deprecated | Required parameter $meta_value follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:168
Deprecated | Required parameter $type follows optional parameter $object_id  || wp-content/plugins/glotpress/gp-includes/meta.php:168

**Comment by ocean90** [comment]
Duplicate of #1446.
