### ISSUE TITLE
Set as old the previous translations with waiting status for this user

### ISSUE THREAD

**Issue by amieiro** [GlotPress/GlotPress-WP#1535]
When a translator suggests more than 1 translation for the same original, the previous ones maintain the `waiting` status. I think we should set the previous translation as `old`, because the new suggestion has improved the previous ones.

### Current status

* User 1 suggests the 1st translation. This translation is in  `waiting` status.
* User 1 suggests the 2nd translation for the same original. The 1st and the 2nd translation are in `waiting` status.
* User 1 suggests the 3rd translation for the same original. The 1st, the 2nd and the 3rd translations are in `waiting` status.

![image](https://user-images.githubusercontent.com/1667814/204568172-d4dc28ac-a0b7-449a-be4e-1b77937f1b09.png)

### Desired status

The desired status is: 
* User 1 suggests the 1st translation. This translation is in  `waiting` status.
* User 1 suggests the 2nd translation for the same original. The 2nd translation is in `waiting` status. The 1st translation becomes `old`. 
* User 1 suggests the 3rd translation for the same original. The 3rd translation is in `waiting` status. The 1st and the 2nd translations become `old`. 

### Other users

This new workflow only affects the translations for this user and for this original string. If another user has suggested a translation for the same original, it doesn't affect.

**Comment by pedro-mendonca** [comment]
Isn't this related to the issue https://github.com/GlotPress/GlotPress/issues/1498 ?

**Comment by amieiro** [comment]
> Isn't this related to the issue #1498 ?

Yes 🤦‍♂️. I am going to close it and I will change the reference in the PR.
