### ISSUE TITLE
Change the colour of "Changes requested"

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1539]
Currently if you already have approved strings they become green, but when you then request changes, the colour is also set to green.
That is confusing as you then cannot see which one is the approved one, and which one is the one with changes requested

**Comment by amieiro** [comment]
I have tested this problem and it works fine. I did these steps:
- Select the translated strings in the top menu.
- Open the first translation.
- Add a comment and click on "Request changes".

The translation becomes blue, but after requesting changes, GlotPress selects the next translation.

I tested this at translate.wordpress.org 

![image](https://user-images.githubusercontent.com/1667814/208414300-a6bd4b06-1b1a-47d9-9fa5-66bb92ba404e.png)

And in a standalone GlotPress site

![image](https://user-images.githubusercontent.com/1667814/208414415-32779f51-54d7-4e7a-b0dd-eba61f6c9355.png)

**Comment by psmits1567** [comment]
My apologies I should have tested this without WP Translation Filler active. It is caused by WP Translation Filler setting the normal color for "Approved". So the change in status needs to be checked again with this new function for Discussion
