### ISSUE TITLE
If you export the glossary, then chars as "'" are converted to old style char handling

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1562]
If the glossary contains pages, pagina's ,noun, then the "'" char is converted to old style WordPress ->pages,pagina&#39;s,noun,
This is unwanted behavior as the glossary is used to indicate missing verbs in several addons
Now it gives an incorrect warning if the translation contains the verb "pagina's", which is currently the normal translation

**Comment by psmits1567** [comment]
When is this going to be fixed as it is annoying

**Comment by pedro-mendonca** [comment]
Hi @psmits1567 
Can you add a step by step test to be able to reproduce?

**Comment by psmits1567** [comment]
That is easy
Select the Dutch translation environment
Then select glossary
The glossary contains one entry "pages" -> "pagina's"
Export this glossary, check the "pages" entry for the translation

**Comment by pedro-mendonca** [comment]
I'm on GlotPress 4.0.0, and this is the result of my test:

### Original string
`Pages word test`

![imagem](https://github.com/GlotPress/GlotPress/assets/7371591/90391ecb-3c17-4a15-962a-f56a3c636b4d)

### Glossary entry
Original term: `pages`
Part of speech: `noun`
Translation: `pagina's`

![imagem](https://github.com/GlotPress/GlotPress/assets/7371591/7c6244b0-4e19-4bfa-b306-f9efc25666a6)

### Exported glossary to CSV

```csv
en,nl,pos,description
pages,pagina's,noun,
```

The exported result is "pages" -> "pagina's", as it's supposed.

**Comment by psmits1567** [comment]
You do not understand my point, because if I open the glossary, then it looks fine. But if you export the file, and check the results, then it is wrong
It is exported as pages,pagina&#39;s,noun,

**Comment by psmits1567** [comment]
Here the html code is not used but the code is "pagina&#39;s"

**Comment by psmits1567** [comment]
& # 39 ;s

**Comment by pedro-mendonca** [comment]
Yes, I see that the exported item is exactly "pagina's" as introduced.
Why should it be converted?
I've imported the same CSV and works just fine.

**Comment by psmits1567** [comment]
No on my environment it is not "pagina's" when exported, it is "pagina& #39 ; s" without the spaces in the text
What is different on your environment??

**Comment by pedro-mendonca** [comment]
I'm on WP 6.5-RC1, GP4.0.0, on a local install on Windows.

**Comment by pedro-mendonca** [comment]
I've now tested with both glossary entries:
- `pagina's`
- `pagina’s`

![imagem](https://github.com/GlotPress/GlotPress/assets/7371591/e90e07e1-3a1d-4c92-9eb4-e86aab26baf2)


Export result:
```csv
en,nl,pos,description
pages,pagina's,noun,
pages,"pagina’s",noun,
```

**Comment by psmits1567** [comment]
Odd any idea where this is caused in my system?

**Comment by pedro-mendonca** [comment]
Can you explain what is your system, versions of active plugins, etc?

**Comment by psmits1567** [comment]
My system is
Windows 10
Latest WordPress
Several plugins active, but the export from translate.wordpress.org is not depending on my plugins

**Comment by pedro-mendonca** [comment]
What do you mean by "the export from translate.wordpress.org"?

**Comment by pedro-mendonca** [comment]
Can you please test that issue on a new latest WP and latest GlotPress, with a new project and glossary?

**Comment by psmits1567** [comment]
Just tested on my mobile with Android
Got the same result
This is the link to the glossary
https://translate.wordpress.org/locale/nl/default/glossary/

**Comment by psmits1567** [comment]
[--locale-nl-glossary (1).csv](https://github.com/GlotPress/GlotPress/files/14588246/--locale-nl-glossary.1.csv)

**Comment by pedro-mendonca** [comment]
I was asking for the environment of the install, not your local client.
Being an export from w.org, it's not a plain GP4 install.
Still, I've managed to use this glossary in a test, seems that your entry is being added as `pagina&#39;s` in the database.
Are you able to edit that entry, writing it again in plain `pagina's` format and check what happens on export again?

**Comment by psmits1567** [comment]
The install is running on translate.wordpress.org not any local environment! I have no access to the glossary on translate.wordpress.org, so I cannot test what you ask me to do

**Comment by amieiro** [comment]
I was able to reproduce the problem. 

I have downloaded the official glossary from https://translate.wordpress.org/locale/nl/default/glossary/, on the bottom link. This is the `pages` line in my local file.

![image](https://github.com/GlotPress/GlotPress/assets/1667814/6f6c910a-09f0-470e-af20-04ecf0e2fc81)

Then I imported to the Dutch local glossary and it is shown fine. 

![image](https://github.com/GlotPress/GlotPress/assets/1667814/baeaeda9-325d-4b2a-bf46-6792b214fddf)

But when I try to see it in the translation environment, it shows me the `page` and `pages` suggestion, and the last one with the `pagina&#39;s`, not with the `pagina's` text.

![image](https://github.com/GlotPress/GlotPress/assets/1667814/2a018635-d95a-40c3-8b2c-99b47342dd0b)

**Comment by pedro-mendonca** [comment]
That's the same issue I get on a brand new install of GP with the current https://translate.wordpress.org/locale/nl/default/glossary/ glossary.

The entrie was inserted as `pagina&#39;s` in the database. I think that's the problem.
The entry is from 2014, I'm not sure how was the entry editor by then, but I suggest some GTE just edit that entry.
I see no issue here. It's added as `pagina&#39;s`, of course it will be exported the same.

**Comment by jeroenrotty** [comment]
Resaved the entry and did a new export, now the entry is correct:
`pages,pagina's,noun,`

**Comment by pedro-mendonca** [comment]
Thanks @jeroenrotty for helping out!

So it's not an export conversion issue, the export works just as expected.

In fact the entry was `pagina&#39;s` but as it's rendered as `pagina's` on the browser it's not easy to spot.

I the end it's all working, despite how it was initially written in the editor/db, it matches correctly, and it works on export and import as desired.

**Comment by psmits1567** [comment]
Tested it again, and now I do get the proper export.
The entry has indeed been changed by a GTE to meet modern WordPress behavior
