### ISSUE TITLE
if an original contains a glossary verb between %sreview%s then it is not indicated as glossary verb 

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1570]
review is a glossary verb, so normally wthin an original it is marked as glossary verb. But when it is between placeholders it is not indicated as such.

**Comment by pedro-mendonca** [comment]
Hi @psmits1567 
Can you show some detailed example? From what I've checked, the placeholder **after** on the word ending boundary is working (eg: `review%s`), and only fails if there is a placeholder in the **starting** word boundary (eg: `%sreview` or `%sreview%s`).

**Comment by pedro-mendonca** [comment]
@psmits1567 it's fixed on #1620

**Comment by psmits1567** [comment]
Thanks👍

**Comment by amieiro** [comment]
This was fixed in https://github.com/GlotPress/GlotPress/pull/1696, so I close this PR. Thank you for catching the bug.
