### ISSUE TITLE
Error when bulk saving waiting strings

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1574]
How to reproduce:
1. Open en project with waiting strings in stable
2. Select all waiting string
3. Select "Approve"
4. Select "Apply"

Preserve you log otherwise it will be gone
Tested on Chrome

**Comment by psmits1567** [comment]
![image](https://user-images.githubusercontent.com/28138634/220621964-cd15b460-0bee-4924-9311-1ac71637abb4.png)

**Comment by amieiro** [comment]
@psmits1567 I was able to reproduce this error, but the strings were approved without any problem. Do you have any problems approving the waiting strings? Or another problem?

As Peter commented, it is important to enable the "Preserve log upon navigation" to see the error in the developer tools (Chrome).

![image](https://user-images.githubusercontent.com/1667814/220657270-de3ecf9a-4807-4a53-a610-116d6a4e8826.png)

**Comment by psmits1567** [comment]
Hi Jesus, the waiting strings are indeed approved. But the error should not be created.

**Comment by amieiro** [comment]
Hi, Peter:

Thank you for the feedback. I have notified to @trymebytes about this and he is reviewing the issue. We will inform you here when we will have any update about this issue.

**Comment by trymebytes** [comment]
Hello @psmits1567, we did a release this week which included a fix by @amieiro, and since then, this does not happen again. Can you please confirm?

**Comment by psmits1567** [comment]
Hi @trymebytes, yes the problem is resolved. Just tested it and I do not see the error anymore
