### ISSUE TITLE
If the last row of the list is translated and saved a javascript error is shown

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1629]
If the last line of untranslated strings is translated and saved the following error is shown
TypeError: $gp.editor.current is null
 /wp-content/plugins/wporg-gp-translation-suggestions/js/translation-suggestions.js?ver=1683883944:59

**Comment by pedro-mendonca** [comment]
This is from a plugin for translations suggestions on translate.wp.org, it's not from GlotPress.
You should report it with a ticket on the WordPress Meta channels.

**Comment by psmits1567** [comment]
Can you indicate where to do that please, I can put it simply in Meta, but that is not the proper method I suspect

**Comment by pedro-mendonca** [comment]
You can add a Meta ticket here:
https://meta.trac.wordpress.org/newticket

You can probably ping @amieiro on the Meta i18n channel on Slack :)

**Comment by psmits1567** [comment]
Ok created a ticket in meta, @amiero will receive the ticket I guess

**Comment by amieiro** [comment]
@psmits1567 I am working on this, so I am going to close this issue, because this ticket is available at https://meta.trac.wordpress.org/ticket/7014 
@pedro-mendonca thank you for the comments.
