### ISSUE TITLE
Large Glossaries cause regular expression limit exhaustion.

### ISSUE THREAD

**Issue by dd32** [GlotPress/GlotPress-WP#1647]
In `map_glossary_entries_to_translation_originals()` it seems like all GlotPress glossary items are put into a single massive regular expression, at some point the maximum regex size limit is hit.

`zh-tw` on Translate.WordPress.org has recently found this limit, causing PHP warnings, and likely the regex to abort without results.

https://github.com/GlotPress/GlotPress/blob/b42f0f66550cdb355247553a9d3cfc76fbaead80/gp-templates/helper-functions.php#L220-L221

`GET https://translate.wordpress.org/projects/............/zh-tw/default/`
`E_WARNING: preg_split(): Compilation failed: regular expression is too large at offset 32813 in wp-content/plugins/glotpress/gp-templates/helper-functions.php:221`

**Comment by amieiro** [comment]
Fixed in https://github.com/GlotPress/GlotPress/pull/1651.
