### ISSUE TITLE
Fix button margins after #1451

### ISSUE THREAD

**Issue by samuelsidler** [GlotPress/GlotPress-WP#1676]
Relevant Git Blame: https://github.com/GlotPress/GlotPress/blame/8f793a657e7bacda73f96cad267739cae5c1f334/assets/css/style.css#L336

In #1451, it appears the margins on buttons were changed, but it's unclear why they were changed. The additional margin makes all buttons appear misaligned within GlotPress, where previously they were vertically centred/aligned.

Examples: 
<img width="374" alt="Screenshot 2023-08-18 at 09 01 14" src="https://github.com/GlotPress/GlotPress/assets/4642604/79980292-f53c-4141-acc1-bf377ecbb91f">
<img width="521" alt="Screenshot 2023-08-18 at 09 01 39" src="https://github.com/GlotPress/GlotPress/assets/4642604/73e4a698-45f3-4772-87ab-1d588f799688">

@amieiro: Are there instances where this additional bottom margin is important? If so, can you target those instances specifically? I can't find any instances where this additional bottom margin is necessary.

**Comment by amieiro** [comment]
@samuelsidler if we need the previous change in another instance like translate.w.org, we will do this improvement there, and not here, so it is ok to revert this change. I have checked it and:
- We have this bug.
- The #1677 PR solves this bug.

I am going to approve and merge this PR. 

Thank you!
