### ISSUE TITLE
Cors error when fetching https://s.w.org/favicon.ico?2

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1687]
Because I have my console open and activated show CORS errors, I noticed the following error
When fetching https://s.w.org/favicon.ico?2 the CORS error is shown.
If I copy the link into my browser and fetch it the error is not shown
Access to fetch at 'https://s.w.org/favicon.ico?2' from origin 'https://translate.wordpress.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

GET **https://s.w.org/favicon.ico?2** net::ERR_FAILED 200
o.wbg.__wbg_fetch_ef7a6623d1fcd3b8 @ feature_collector.js:23
$<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hafed46806e9b90db @ wasm_feature.wasm:0x11a2f
$wasm_bindgen_futures::queue::Queue::new::{{closure}}::hea8c094eabab6355 @ wasm_feature.wasm:0x63074
$<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h3808fcbba40aeb8b @ wasm_feature.wasm:0x7f6c4
L @ feature_collector.js:23
i @ feature_collector.js:23
Promise.then (async)
o.wbg.__wbg_then_ce526c837d07b68f @ feature_collector.js:23
$wasm_bindgen_futures::queue::Queue::schedule_task::hf84451605d67b040 @ wasm_feature.wasm:0x742f2
$wasm_bindgen_futures::task::singlethread::Task::spawn::h86155a6203f9cee8 @ wasm_feature.wasm:0x79e9d
$wasm_bindgen_futures::future_to_promise::{{closure}}::hb7c7eb7e6bddda21 @ wasm_feature.wasm:0x79c12
$wasm_bindgen::convert::closures::invoke2_mut::h2d234a120c7f3de5 @ wasm_feature.wasm:0x7f63f
(anonymous) @ feature_collector.js:23
(anonymous) @ feature_collector.js:23
o.wbg.__wbg_new_37705eed627d5ed9 @ feature_collector.js:23
$start @ wasm_feature.wasm:0x7cc6f
main @ feature_collector.js:23
await in main (async)
mainFunction @ feature_collector.js:23
(anonymous) @ feature_collector.js:23

It is the WordPress icon, but if I open the link of the icon showing I get this
https://wordpress.org/
So there is a wrong link within the source I suspect

**Comment by amieiro** [comment]
Hi @psmits1567 

Could you give us the URL where this problem happened, to try to reproduce it? Thank you

**Comment by psmits1567** [comment]
Hi @amieiro on my current location via wifi and external network it does not happen. This weekend I am back home, and will retest it over there again. I noticed some other CORS error has been fixed, so maybe it fixed mine as well.

**Comment by psmits1567** [comment]
@amieiro tested again on my installation that had this issue. The problem is no longer present
