### ISSUE TITLE
404 at /glotpress after installation

### ISSUE THREAD

**Issue by sunshinephotocart** [GlotPress/GlotPress-WP#1720]
## Description
Go to https://www.sunshinephotocart.com/glotpress after installing the plugin and get 404 error.

## Step-by-step reproduction instructions
Install plugin. Go to https://www.sunshinephotocart.com/glotpress.

## Expected behavior
I should see something

## Actual behavior
404 page

## WordPress information
- WordPress version: 6.3.1
- GlotPress version: 3.0.0
- Are all plugins except GlotPress deactivated? Tested with only GlotPress active via Troubleshooting and still 404
- Are you using a default theme (e.g. Twenty Twenty-Three)? Yes during Troubleshooting, still 404

## Device information
- Operating system: macOS
- Browser: Chrome

**Comment by amieiro** [comment]
Hi @sunshinephotocart 

You need to access to https://www.sunshinephotocart.com/glotpress/ , with the slash at the end of the URL.
This is a well-know bug that has been resolved [here](https://github.com/GlotPress/GlotPress/pull/1701) and it will be released in the next stable version.
