### ISSUE TITLE
Glotpress does not recognise %5$s properly depending on translation

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/GlotPress-WP#1728]
Have a look at this original

https://translate.wordpress.org/projects/wp-themes/magazine-news-byte/nl/default/?filters%5Boriginal_id%5D=7866094
Glotpress gives a warning which is not correct see image
The translated line is "op %5$sMenu's opslaan"
The error says unexpected placeholders: p %5 (unescaped %, use %% instead". That is not correct the placeholder %5$s is present!

**Comment by psmits1567** [comment]
![glotpress %5 error](https://github.com/GlotPress/GlotPress/assets/28138634/fe21e463-df35-4863-a413-f4e24161db71)

**Comment by pedro-mendonca** [comment]
There are two, one `%5$Maak` (wrong) and another `%5$sWijzi...` (ok).

If you fix the first `%5$` to `%5$s` it should remove the warning, can you please recheck?

**Comment by pedro-mendonca** [comment]
Just tested with the Portuguese translation:
https://translate.wordpress.org/projects/wp-themes/magazine-news-byte/pt/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=7866094&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc

The placeholders must be checked carefuly, specially if you're using machine translation (DeepL / chatGPT), sometimes it can fail to identify the placeholders correctly. It happened to me with example this string.

So, there is no issue here, can you please recheck @psmits1567 ?

![imagem](https://github.com/GlotPress/GlotPress/assets/7371591/ccf9bc4f-9e47-4fd9-abae-7c6afca54a41)

**Comment by psmits1567** [comment]
@pedro-mendonca, double checked and indeed I missed out the second %5$s placeholder. Would it be possible to highlight the wrong placeholder? It is hard to see where it goes wrong if there are many placeholders.

**Comment by pedro-mendonca** [comment]
I think it's possible yes.
To start there's a PR to highlight the placeholders [here](https://github.com/GlotPress/GlotPress/pull/1620).
Could be added some specific highlithing for missing or extra placeholders.

**Comment by psmits1567** [comment]
Would be a nice feature to prevent people like myself adding issues that are no issues. It is not exactly clear what is already implemented in the PR
