### ISSUE TITLE
Bug in References link: Trac Error, cannot open the link

### ISSUE THREAD

**Issue by Nureli-Tashpolat** [GlotPress/GlotPress-WP#1739]
## Description
When click "References" and tried to open related source code part link, appear Trac Error page with below error message:

> Trac Error
> No node branches/6.3.x/wp-admin/about.php at revision 56631

## Step-by-step reproduction instructions
1. Go to 'https://translate.wordpress.org/projects/wp/6.3.x/admin/ug/default' click to open any String
2. Click on 'References'
3. Scroll down to related source code link and click to open

## Expected behavior
It should be open String related source code part. 

## Screenshots or screen recording (optional)
- https://snipboard.io/cLj3XV.jpg
- https://snipboard.io/8Jwem4.jpg

## WordPress information
- WordPress version: 6.3.x

In addition, I think the root cause of this issue is there is no branch name like 6.3.x, when I change it to 6.3, it can open correct source code page. An example:

- curent missing URL link: https://build.trac.wordpress.org/browser/branches/6.3.x/wp-admin/upload.php?marks=372#L372
- correct one should be: https://build.trac.wordpress.org/browser/branches/6.3/wp-admin/upload.php?marks=372#L372

**Comment by akirk** [comment]
Thanks for reporting but this is a misconfiguration on translate.wordpress.org, not a GlotPress bug. Nevertheless, I was able to change the configuration on translate.wordpress.org, so that it now works as expected.
