### ISSUE TITLE
Version discussion and translation statistics in GlotPress

### ISSUE THREAD

**Issue by criconhelp** [GlotPress/GlotPress-WP#1767]
Hello. Can you please tell me how to implement statistics counting as it is done on the official translate.wordpress.org site?

![Снимок экрана 2024-01-14 064135](https://github.com/GlotPress/GlotPress/assets/32668356/6aadaaf9-38e1-42b4-96f6-f2b710874bcf)

And where to find the same adaptive theme that works well on smartphones?

![Снимок экрана 2024-01-14 074825](https://github.com/GlotPress/GlotPress/assets/32668356/98a58737-3f55-4c50-8043-ba7b5a4adfe2)

**Comment by amieiro** [comment]
The project stats are implemented with this [template](https://github.com/WordPress/wordpress.org/blob/27be351f342467092511905ad636bd1faa59b019/wordpress.org/public_html/wp-content/plugins/wporg-gp-customizations/templates/locale-project.php#L247) and [here](https://github.com/WordPress/wordpress.org/blob/27be351f342467092511905ad636bd1faa59b019/wordpress.org/public_html/wp-content/plugins/wporg-gp-routes/inc/routes/class-locale.php#L222) is where we call the template.

In the GlotPress editor, we have some hotkeys to move to the next and previous rows:
- Page Up or Ctrl-Up Arrow to move to the next row.
- Page Down or Ctrl-Down Arrow to move to the previous row.

These arrows are implemented in [this customized template](https://github.com/WordPress/wordpress.org/blob/27be351f342467092511905ad636bd1faa59b019/wordpress.org/public_html/wp-content/plugins/wporg-gp-customizations/templates/translation-row-editor.php#L80) for translate.w.org,

**Comment by criconhelp** [comment]
Thank you very much for showing me.
