### ISSUE TITLE
Cascading warnings from input on array functions

### ISSUE THREAD

**Issue by pkevan** [GlotPress/GlotPress-WP#1813]
## Description
Cascading warnings from input on array functions.

Many hundreds of these happen each day, so it creates unnecessary noise in the dotorg warnings channels.

## Step-by-step reproduction instructions
```
E_WARNING: explode() expects parameter 2 to be string, array given in [..]/wp-content/plugins/glotpress/gp-templates/translations.php:290
```

```
E_WARNING: in_array() expects parameter 2 to be array, null given in [..]/wp-content/plugins/glotpress/gp-templates/translations.php:293
```

The above warning then runs on L297, 301, 305, 309, 314, 319

## Expected behavior
No warnings should appear when values isn't an array.

## WordPress information
- WordPress version: trunk (wp.org)
- GlotPress version: latest committed version to wp.org

**Comment by pedro-mendonca** [comment]
The only way I'm able to reproduce this is by adding an array to the `$filters[status]` like this:
`...?filters[status][]=current&filters[status][]=fuzzy`

**Comment by pkevan** [comment]
Most likely coming from pentesters, so not necessarily due to users' interactions.

**Comment by pedro-mendonca** [comment]
I've made a PR suggestion that fallbacks to an empty string if the GET parameter `filter[status]` isn't a string.
