### ISSUE TITLE
PHP8 error in logs, passing NULL to string functions

### ISSUE THREAD

**Issue by afragen** [GlotPress/GlotPress-WP#1858]
## Description
I'm running a GlotPress installation on a site and I constantly see repeating PHP Deprecation warnings for passing NULL to string functions.

```
PHP Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /sites/xxx/files/wp-includes/pomo/po.php on line 270
PHP Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /sites/xxx/files/wp-includes/pomo/po.php on line 271
PHP Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /sites/xxx/files/wp-includes/pomo/po.php on line 127
```

I originally reported this to [Trac 61985](https://core.trac.wordpress.org/ticket/61895) but the consensus was that the issue was upstream in GlotPress.

The issue seems to be with partial translations where there are empty entries in `Translations_Entry->translations`. In GU_Format_PO::print_exported_file() these entries passed to `PO::export()` where string manipulations are performed.

## Step-by-step reproduction instructions
On a site running GlotPress 4.0.1, having some partial translations should trigger the issue. I'm not clear where the issue initiates but I have narrowed it down to the last step in GlotPress of running `GP_Format_PO::print_exported_file()`.

## Expected behavior
No PHP deprecation notices.

## Actual behavior
Log filled with PHP deprecation notices as above.

### Environment
- WordPress: 6.6.1
- PHP: 8.3.10
- Server: nginx/1.26.1
- Database: mysqli (Server: 8.0.39-0ubuntu0.24.04.1 / Client: mysqlnd 8.3.10)
- Browser: Safari 17.6 (macOS)
- Theme: Twenty Twenty-Four 1.2
- MU-Plugins: 
  * SpinupWP Debug Log Path 1.0
  * WP Migrate DB Pro Compatibility 1.2
- Plugins: 
  * Auto-Flush Object Cache 0.7.1
  * Git Updater - Gist 2.0.3
  * Git Updater 12.5.0
  * GlotPress 4.0.1
  * GlotPress for Git Updater 0.1
  * Limit Login Attempts Reloaded 2.26.12
  * Query Monitor 3.16.4
  * Registration Honeypot 1.0.0
  * SpinupWP 1.7.1
  * Stop Auto-update Success Email 0.5.1
  * What The Cron 0.1.2
  * WordPress Beta Tester 3.5.6
  * WP Debugging 2.11.24
  * WP Mail SMTP 4.1.1
  * WP Mail SMTP Settings 0.6.0
  * WP Migrate 2.6.13
  * Zero Spam for WordPress 5.5.7

## Mitigation
I'm not certain that I have the correct solution for this issue but my solution is to convert any NULL entries in the `Translations_Entry->translations` array to an empty string within `GP_Format_PO::print_exported_file()`. I have a working plugin with this fix. https://gist.github.com/afragen/acf808925400dc8a0544fd9611ff2189

**Comment by amieiro** [comment]
Tested on 6.6.2 with PHP 8.1, trying to export and .po file in a project with empty translations, and I got the same error:

```
PHP Deprecated:  substr(): Passing null to parameter #1 ($string) of type string is deprecated in wp/wp-includes/pomo/po.php on line 270
PHP Deprecated:  substr(): Passing null to parameter #1 ($string) of type string is deprecated in wp/wp-includes/pomo/po.php on line 271
PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in wp/wp-includes/pomo/po.php on line 127
```
