### ISSUE TITLE
Copy from original should be a button

### ISSUE THREAD

**Issue by yoavf** [GlotPress/GlotPress-WP#681]
To better match expected UI patterns, the copy from original link beneath the textarea should look like a button. Additionally, we should hide it if the textarea has already been edited.

**Comment by toolstack** [comment]
I would agree except that we break that convention in several places.  The new design should address this but until then I'd leave it alone.

Or if it's really an issue, go through and change all the instances of this kind of link/button behaviour.

**Comment by toolstack** [comment]
Resolved as part of #928.
