### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by c-schmitz** [GlotPress/GlotPress-WP#693]
It would be great if GlotPress could support some kind of spellchecking, especially on existing translations (during translating I'd guess the browser could do that).

**Comment by swissspidy** [comment]
During office hours today it was suggested to implement https://www.languagetool.org/, an open-source proof-reading tool.

We agreed that it made most sense to start this off as a plugin first.

**Comment by ocean90** [comment]
A plugin would be great, closing as _maybelater_.
