### ISSUE TITLE
Missing Expected URLs due to newline character

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#700]
Hello,

I've noticed this a few times when translating, if the original has a URL which is followed by a new line character than the system thinks the original URL isn't present in the translated string;
![screen shot 2017-04-17 at 11 51 27 am](https://cloud.githubusercontent.com/assets/8726005/25100267/4a6df140-2364-11e7-8fa7-6db2adc0e21b.png)
Permalink - https://translate.wordpress.org/projects/apps/ios/release-notes/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=135168&filters%5Btranslation_id%5D=48554857

These entries stay under Warnings until you discard the warning.

IMO the newlines shouldn't be taken into account when validating URLs.

Cheers

**Comment by ocean90** [comment]
Thanks for the report. Warnings for URLs is a feature on translate.wordpress.org and not part of GlotPress core. This needs to be reported on meta.trac.wordpress.org, as you already did: https://meta.trac.wordpress.org/ticket/1401

**Comment by garretthyder** [comment]
Thanks @ocean90, sorry about that. Had been pointed to this repo for logging issues with GlotPress so recreated here in case, thanks for pointing out that feature is a meta item. Cheers
