### ISSUE TITLE
Make glossary entries case insensitive

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#703]
Hello,

With Glotpress Glossary the words within the glossary are underlined on the original string making it easier to see what should be translated. That's especially helpful with the flavoured english translations (Canadian, a=Australian, etc). But currently they're all case sensitive so if you have color>colour in the glossary but it's a single word string for Color then it won't be underlined. 

Would be nice if glossary terms are case-insensitive. Please let me know if this won't be picked up anytime soon as I'll manually add capitalized versions to the Glossary.

Thank you
Original meta.trac ticket - https://meta.trac.wordpress.org/ticket/2778

**Comment by webaware** [comment]
IME, this is not true. Terms are case-insensitive. Perhaps provide an example of a failure, because there could be another factor (e.g. not being detected as a whole word correctly, due to parentheses)

**Comment by garretthyder** [comment]
Hi @webaware,
The original trac ticket has some examples - https://meta.trac.wordpress.org/ticket/2778
Do you have the GlotDict extension installed by chance, as netweb indicated in the trac ticket he had the same initial assumption but upon disabling the GlotDict extension was able to reproduce the issue.
*Also I've seen some Glossaries out there with both lower and capitalized versions, which if we make case insensitive won't be required any longer.
Thanks

**Comment by toolstack** [comment]
I can confirm the glossary matching is case sensitive, it's an easy technical fix.

**Comment by garretthyder** [comment]
Thanks @toolstack

**Comment by webaware** [comment]
Ah yes, indeed I have GlotDict. My bad for not reading the trac ticket.

**Comment by garretthyder** [comment]
All good @webaware, was my bad for not posting here originally
