### ISSUE TITLE
Glossary Term highlighting disappears after interacting with an entry

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#704]
Hello,

Wanted to flag a minor issue with the Glossary term highlighting on strings. When initially viewing a string you'll note the glossary terms are underlined appropriately, however if you act on the item rejecting, etc. And then click details again to expand it the terms are no longer highlighted/underlined.

Below screen is after I rejected the translated string, as can be seen the glossary terms for catalog are no longer underlined;
http://i.imgur.com/gmUa5Ns.png

Reloading the page after submitting a translated string I can see it's re-underlined;
http://i.imgur.com/aLvTwnS.png

Since Reject seems to be done via ajax and the glossary is php, maybe on ajax updates we need a js script to re-glossary/underline terms.
*That's an assumption as I don't know nearly enough about how it works.

Let me know if you need any clarification,
Cheers
Original meta.trac ticket - https://meta.trac.wordpress.org/ticket/2785

**Comment by toolstack** [comment]
I've confirmed this is a bug and have a fix, it's not js related, there's a missing PHP function call during the ajax load to mark glossary terms.
