### ISSUE TITLE
Edited translation not taken after "approve"

### ISSUE THREAD

**Issue by ghost** [GlotPress/GlotPress-WP#707]
There is an existing unapproved translation. 
I see an error in it, correct it and hit "approve".
The prior, faulty translation will be approved then instead of the changed translation.

**Comment by tobifjellner** [comment]
This is a user interface issue. The Approve button (to the right) will approve whatever text was suggested before, when you loaded the page.
When you change anything, you have to hit the button Add new (below).
I guess UI could be improved here. For instance, JS could disable the "approve" button as soon as anything is edited.

**Comment by toolstack** [comment]
I've added a PR that throws an error when clicking on any of the status change buttons if the translation has been changed.

By no means is this the only way to do it, as mentioned above the buttons could be disabled, but that is a more complex solution and should be looked at during the UI redesign.
