### ISSUE TITLE
Contact Details for PTE/GTE

### ISSUE THREAD

**Issue by sebastienserre** [GlotPress/GlotPress-WP#712]
Hello,
I wonder if it should be possible to add a link to contact a translator?
I'm PTE and some contributors are contributing with litle mistake. I correct but will be usefull to tell him rules...
Should be great if PTE could have access to mail addess or something to contact a traductor.

**Comment by chantalcoolsma** [comment]
#324

**Comment by ocean90** [comment]
GlotPress has no PTE/GTE roles, that's specific to translate.w.org. Each install might have a different translation community with different contact possibilities so that needs to be handled individually. It's nothing that GlotPress core should provide by default.
