### ISSUE TITLE
Support secondary sources

### ISSUE THREAD

**Issue by qdinar** [GlotPress/GlotPress-WP#713]
it would be good if people can translate from french, russian etc.

**Comment by toolstack** [comment]
Unfortunately that leads to a game of [telephone](https://en.wikipedia.org/wiki/Chinese_whispers) that results in low quality translations.

Translation really needs to be done from the source language to the destination language without any intermediary steps getting in the way.

**Comment by toolstack** [comment]
@ocean90 unless you have a different thought I'd suggest we close this as a wontfix.

**Comment by qdinar** [comment]
(and i wanted say but was lazy to write an evident thing). there can be reviewer who knows source language. he can easily accept most of translations, and edit which are not correct. so translation can go faster.

**Comment by ocean90** [comment]
The way how GlotPress currently works doesn't allow us to use a different source than the default. This might be something for the future in another form like showing translations of other locales in another tab but for now I'm going to close this as a wontfix.
