### ISSUE TITLE
Enhancement Request - Clear the page parameter when filter changes the current view

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#718]
Hello,

This is part bug cause it's undesirable but can be seen more as an enhancement as technically nothing is broken.

But right now if you are deep in the pagination on a view and switch your view the new view will load at the same pagination depth. Where this becomes an issue is when the view you switch to has less pages than the original view you get presented with the message 'No projects found.' which confuses the user but also when this message is presented the pagination is hidden so there's no way (aside from editing the URL) to navigate to the existing pages.

IMHO when the view filter is used the page param should be dropped so the new view always loads on the first page.

Steps to reproduce;
1. Login to translate.wordpress.org
2. Choose a locale
3. Go to the Plugins tab
4. Dive into page 10
5. Use the filter dropdown to change to the waiting view
6. Note the message and lack of pagination and in URL the page param is still there.
*If you have more than 10 pages of waiting strings then go to a deeper page.

Hope that makes sense,
Cheers

**Comment by toolstack** [comment]
I can't reproduce this issue on a standalone install of GP.

@ocean90 does translate.w.org do anything weird with pagination?

**Comment by ocean90** [comment]
Yeah, [that page](https://translate.wordpress.org/locale/de) doesn't exist in a default GP install.

**Comment by garretthyder** [comment]
Thanks @ocean90 I've moved this to Meta Trac here - https://meta.trac.wordpress.org/ticket/2829
