### ISSUE TITLE
When Singular Term in Glossary but Plural Term in string gets highlighted with single value

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#721]
Hello,

I noticed this while translating en_CA, the word honors was underlined and hovering showed the suggested Glossary value of honour rather than honours.
![screen shot 2017-05-24 at 11 45 25 am](https://cloud.githubusercontent.com/assets/8726005/26428632/aab65ba0-4097-11e7-8a99-cbc86792eca3.png)

Checking the Glossary the term honors wasn't listed, so the question is when the singular version of the word is available in the Glossary should it be highlighting the plural version in strings like seen above?

I've since added the plural version to the glossary.

Thoughts? I feel if the term isn't there in full it shouldn't be highlighted.
Thanks

**Comment by garretthyder** [comment]
Note: Now that I added honors to the Glossary I see two entries in the tooltip;
![screen shot 2017-05-24 at 4 32 32 pm](https://cloud.githubusercontent.com/assets/8726005/26429901/a9664524-409e-11e7-82f5-a67414d6fad1.png)

**Comment by toolstack** [comment]
Currently the code checks for several variations:

- term
- term + 's'
- term + 'es'
- term + 'ies' if the term ends in y
- term + 'ves' if the term ends in f or fe
- term + 'ies' if the term ends in y
- term + 'en' if the term ends in an

If any of the above are match a string in the translation, the glossary term tooltip will appear.

As to if this should be the behaviour, I think on average it's probably the correct way at the moment.

The upside is that in most cases (where the originals are in English) this will simplify a translators job.  The glossary is just a guide after all.

The downside is that for non English originals this could give the wrong glossary terms.

**Comment by garretthyder** [comment]
Thanks @toolstack that makes sense for sure. I see that being beneficial in alot of cases. 

I have two thoughts on enhancements to it;
1. In the tooltip show the replacement term appended with the same variation suffix. So if it matched term + 's', then should show translation + 's' instead of just translation.
2. If there's an exact match then skip the variation checks, right now it's showing two in the tooltip, the exact match and the variation match.

Thoughts?

**Comment by toolstack** [comment]
1. The problem with that is the language may have different rules than English for the appendices so you can't programmatically just add them.

2. Normally you'd only add the base variation of the word so you'd never see the second tooltip.  In cases where you do add the variations there may be valid reasons to show both (perhaps a language specific quirk).

**Comment by garretthyder** [comment]
Thanks @toolstack good points for sure. I'll leave it to you to determine the fate of this ticket

**Comment by toolstack** [comment]
I'm going to mark it as `wontfix` and close it for now, we can always come back to it if things change.
