### ISSUE TITLE
Misspelled action and incorrect comment in GP_Original::closest_original()

### ISSUE THREAD

**Issue by SergeyBiryukov** [GlotPress/GlotPress-WP#729]
Found two issues in `GP_Original::closest_original()`:
* The `gp_post_string_similiary_test` action is misspelled, I think it should be `gp_post_string_similarity_test`.
* The comment says: "Fires before determining string similarity", but it fires after determining the similarity, not before.

**Comment by ocean90** [comment]
Introduced in https://glotpress.trac.wordpress.org/changeset/1032.

@yoavf Does wp.com use the action?

**Comment by toolstack** [comment]
I added the 3.0 milestone to this as it is an API breaking change.

Otherwise it looks good to me.

**Comment by yoavf** [comment]
> @yoavf Does wp.com use the action?

I don't think we are. Thanks for catching this @SergeyBiryukov
