### ISSUE TITLE
Export - only matching the filter fail

### ISSUE THREAD

**Issue by mobby2561** [GlotPress/GlotPress-WP#732]
If the only matching the filter is chosen it exports ony current trnaslations (for status _Current/waiting/fuzzy + untranslated (All)_)

**Comment by toolstack** [comment]
Confirmed that "only matching filter" is broken, the JavaScript does not add the filter parameters to the link before calling the link.

**Comment by toolstack** [comment]
Associated code is here: https://github.com/GlotPress/GlotPress-WP/blob/develop/assets/js/translations-page.js#L31

**Comment by toolstack** [comment]
Turns out this isn't in the JavaScript, but instead in the default value used in `for_export()`.  This bug only happens if you have not applied a filter already.  If you have applied a filter, the export will function as expected.
