### ISSUE TITLE
Add string counts to the filter links

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#733]
Hello,

Wanted to suggest adding string counts to the filter links;
![screen shot 2017-06-14 at 9 27 53 am](https://user-images.githubusercontent.com/8726005/27143654-f7ed656a-50e3-11e7-9b68-fcada9488440.png)

Thanks

**Comment by toolstack** [comment]
It's possible to do but it would have a performance impact as we only load the strings required for a given page from SQL and not the entire translation set.

Getting the totals would require several more SQL statements.

**Comment by garretthyder** [comment]
I can see the performance issue there forsure, if it's about page load over server load they could be introduced through ajax if there was an endpoint to call for counts.
And maybe if not worthy of GlotPress itself the GlotDict extension could introduce for the seasoned translators

**Comment by garretthyder** [comment]
Awesome thanks @toolstack & @ocean90
