### ISSUE TITLE
Add ed/ing suffixes to the Glossary variation highlighting

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#734]
Hello,

This ticket started as a Slack discussion;
https://wordpress.slack.com/archives/C02RP4R9F/p1497458337971748

Currently, there are certain suffixes on words like 's' for plurals which are see as Glossary variations and get highlighted accordingly.

I would like to suggest both the 'ed' and 'ing' suffixes also be treated in the same fashion.

Examples with these suffix in strings;
Permalink to 'ed' suffix in string - https://translate.wordpress.org/projects/wp-plugins/xllentech-english-islamic-calendar/dev-readme/en-ca/default?filters%5Boriginal_id%5D=4648183
Permalink to 'ing' suffix in string - https://translate.wordpress.org/projects/wp-plugins/nextgen-gallery/dev-readme/en-ca/default?filters%5Boriginal_id%5D=4645408

Thank you

**Comment by toolstack** [comment]
See associated code here: https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-templates/helper-functions.php#L78

**Comment by garretthyder** [comment]
Thanks @toolstack & @ocean90
