### ISSUE TITLE
Project glossary on project level instead of subproject

### ISSUE THREAD

**Issue by jobthomas** [GlotPress/GlotPress-WP#736]
At the moment, glossaries for projects are added to subproject instead of project level. For example, for WooCommerce stable we have a glossary but not for trunk:

Stable:
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/nl/default

![http://cld.wthms.co/BMn3O](http://cld.wthms.co/BMn3O+)
Link to image here: http://cld.wthms.co/BMn3O.

Dev: 
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/nl/default

![http://cld.wthms.co/w3Hr6h](http://cld.wthms.co/w3Hr6h+)
Link to image here: http://cld.wthms.co/w3Hr6h.

It would be great if this could be added on the project level, below the locale glossary for example:

![http://cld.wthms.co/pP1AmU](http://cld.wthms.co/pP1AmU+)
Link to image here: http://cld.wthms.co/pP1AmU.

cc @ePascalC

**Comment by ocean90** [comment]
Since this about translate.w.org, a ticket on https://meta.trac.wordpress.org should be opened.
