### ISSUE TITLE
Standalone word not picked up by Glossary Highlighting

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#742]
Hello,

Just wanted to flag that when a term is by itself in a string and has a Glossary term it's not picked up. Or maybe it's because it's capitalized, hard for me to say.

Permalink - https://translate.wordpress.org/projects/wp-plugins/paid-member-subscriptions/dev/en-ca/default?filters%5Boriginal_id%5D=4676698

Cheers

**Comment by garretthyder** [comment]
I assumed incorrectly this isn't about it being a Standalone word, so going with it's either because it's capitalized or maybe because it's the first word in the string.
Here's another case - https://translate.wordpress.org/projects/wp-plugins/live-weather-station/dev/en-ca/default?filters%5Boriginal_id%5D=4667562

**Comment by toolstack** [comment]
See #703, known issue and already has a PR merged to resolve.  It will be included in the next release.

**Comment by garretthyder** [comment]
Thanks @toolstack sorry my bad, thought it was slightly different but you're right they're the same case insensitivity issue.
