### ISSUE TITLE
Add link to consitency tool in the original string

### ISSUE THREAD

**Issue by Mte90** [GlotPress/GlotPress-WP#752]
Actually I add a link to consistency tool for the term and locale only on term that have the tooltip of a glossary item, but I think that is not enough and we need to add a link in all the terms with more of 4 char. In that way we can motivate people to use the tool and also improve the glossary because they will open more probably the consistency. 
Maybe add a link in all the terms can be confusing on UI but maybe the link can be open with a right click as example.

**Comment by ocean90** [comment]
The consistency tool is not part of GlotPress.

**Comment by Mte90** [comment]
Uh I didn't know that, I will keep that feature on glotdict :-)

**Comment by garretthyder** [comment]
I've posted this to meta if that team ends up wanting to incorporate the functionality;
https://meta.trac.wordpress.org/ticket/2915
