### ISSUE TITLE
Copy with Glossary Translation

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#754]
Hey Guys,

This might be better to test on GlotDict before migrating to GlotPress so pinging @Mte90

The feature he implemented and mentioned in #750 gave me the idea as I found that right click a bit clunky as the term ends up just in the text box or at the end of existing text so if you unintentionally click it can inject unwanted text.

My feature request is similar but affects the whole string, so it would be to add another link beside the 'Copy from Original' that was labeled 'Copy with Translation' which would copy the original string with the exception of the glossary terms within the string they're all replaced during the copy process with their glossary replacement.

I would find this especially helpful with en_CA as 99% of strings containing a term will be identical on translation with the exception of the glossary term.

Hope that makes sense,
Cheers

**Comment by toolstack** [comment]
The only concern I'd have with this is that because we match glossary term variations, it may be very error prone if the translator doesn't pay close attention to the translation.

**Comment by garretthyder** [comment]
Thanks @toolstack I can see the concern. Maybe we place a tooltip on the link with the warning or generate a warning for the string that's controlled by a cookie so it only occurs the first time.
If possible would be nice if the variation is what gets used, and if that's not possible maybe a warning that the copied string is using the root term but we notice that it is a variant so inject a warning there.

**Comment by toolstack** [comment]
We can't use the variations as if we match, say, "Coloring" in the source to a glossary term of "Color", how would we convert the glossary term to Japanese?  Or any other language that isn't English 😃 

Each language has it's own grammar rules for those variations.

We wouldn't want to use a cookie as if someone adds the translation but can't accept it, we'd want the warning to show up on the approver's view of the entry as well.

**Comment by garretthyder** [comment]
Good point, I guess if we carry over either the root or a variation we'll want a discardable warning rather than one controlled by cookies.

**Comment by Mte90** [comment]
I think that this behaviour can be helpful for english variation but not for all because probably the word order is different so a manual way with click is the best behaviour.

**Comment by ocean90** [comment]
That indeed sounds like something for GlotDict and is only useful for English variants which is a minority of our users. So I'm going to close this as _maybelater_, depending on whether we'll support per-locale settings at some point.

**Comment by toolstack** [comment]
It could be useful for non English translations as a starting point, but perhaps as a plugin to start.
