### ISSUE TITLE
Feature Request: Copy with Google Translation

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#755]
Hello,

A similar request as #754 but integrating Google Translation API to introduce a 'Copy with Google Translation' link that would take the original string and the source/destination locales to make a request to Google Translate API and using the response (if success) as the string copied into the text area.

Of course it won't be perfect translations as they're from Google but might help reduce typing for some languages where all words change.

Possibly better to implement on GlotDict so pinging @Mte90

Thanks

**Comment by toolstack** [comment]
Already implemented as a plugin (https://wordpress.org/plugins/gp-machine-translate/).  

The Google API is no longer free so unlikely to be brought in to core.

**Comment by garretthyder** [comment]
AMAZING, I was thinking about building something through GlotDict, but that's awesome. Thanks @toolstack no need for it in core as not all languages are supported anyway so would just be bloat.
Closing, reopen if that's not what I should be doing here.
Thanks
