### ISSUE TITLE
Add validation for Glossary Terms where Translation matches Original term

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#756]
Currently, if you create a Glossary entry where the Translation matches the Original term it gets created without issue. Would be nice to add some validation that would block this with an error message.

Very edge case, I only did it cause I missed changing the translation string and accidentally had it the same.

**Comment by ocean90** [comment]
Closing as wontfix since it's not unusual in non-English languages to define a term which is exactly the same as the original.

**Comment by garretthyder** [comment]
Thanks @ocean90 that's interesting, maybe a warning would be better so it doesn't block non-english
