### ISSUE TITLE
Add link to Consistency tool from Glossary Terms

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#757]
Hello,

Wanted to suggest a feature to tie the Glossary to the Consistency tool so when viewing the Glossary you can check Glossary Terms via the Consistency tool. 

A good placement would either be as a column or another link beside details, or within the Meta when a Glossary Term is expanded.

Cheers

**Comment by toolstack** [comment]
The consistency tool isn't part of GlotPress.  You probably need to open this as a ticket on meta-i18n.

**Comment by garretthyder** [comment]
Sorry guys, opened on trac - https://meta.trac.wordpress.org/ticket/2905#ticket
