### ISSUE TITLE
Hover over Glossary term adds text to base of page

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#758]
Hello,

Minor bug I came across when you hover over a Glossary term the tooltip appears but also at the base of the page some text gets injected;
![screen shot 2017-06-28 at 2 52 01 pm](https://user-images.githubusercontent.com/8726005/27662351-4d1f46dc-5c12-11e7-9a13-364365eadf5a.png)
(find the verbcolour as the base of the screenshot)

Inspecting that section here's the HTML that string comes from;
<div role="log" aria-live="assertive" aria-relevant="additions" class="ui-helper-hidden-accessible"><div><ul><li><span class="pos">verb</span><span class="translation">colour</span><span class="comment"></span></li></ul></div></div>

This only happens when you hover so must be a JS issue, from looking at the code it looks like that's tooltip template HTML, so maybe the .ui-helper-hidden-accessible class should have a display none on it??

Cheers
P.S. Here's the string I was looking at when it occurred;
https://translate.wordpress.org/projects/wp-plugins/the-events-calendar/stable/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=3887469&filters%5Btranslation_id%5D=48304327
P.P.S. I made sure to disable GlotDict to check the issue was actually GlotPress and not GlotDict

**Comment by toolstack** [comment]
Confirmed, I've replicated this on my development install.

**Comment by toolstack** [comment]
It's a bug in jQuery UI, version 1.10.4 works fine, both 1.11.4 and 1.12.4 exhibit this behaviour.

**Comment by garretthyder** [comment]
Thanks @toolstack I guess a proper fix will come once jQuery UI resolves the issue. For now I found on forums it's suggested to just do a display none on the .ui-helper-hidden-accessible class.

**Comment by toolstack** [comment]
Could you provide the link to the work around?

**Comment by garretthyder** [comment]
Here @toolstack two mentions;
https://stackoverflow.com/a/15894428
https://stackoverflow.com/a/12883114
