### ISSUE TITLE
Feature Request: Flag Misspelling/Grammar issues to plugin/theme author

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#759]
Hello,

It would be really nice to have a consistent way of flagging invalid strings to authors so they can correct the base string. Currently, I either open a support ticket with the author or I fork their repo and make the change myself. A button in the string meta called flag or report that opens a model with a simple textarea to put your note, submitting would generate a notification to the author with permalink to the string along with the translators note.

Thank you

**Comment by vitormadeira** [comment]
That would be a great idea. I totally agree with your suggestion and would like to see such feature being available.

Thank you.

**Comment by toolstack** [comment]
This is probably another one for translate.w.org as the plugin/theme forums are not part of GP.

**Comment by garretthyder** [comment]
Thanks @toolstack I've posted this to the meta trac;
https://meta.trac.wordpress.org/ticket/2913
