### ISSUE TITLE
Block adding Glossary Terms containing punctuation with error/warning

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#768]
Hello,

This issue stems from #762 where it was mentioned that punctuation is stripped when doing a term lookup, as such I'd suggest the Glossary block creation of those terms, and possibly add a way to mark invalid terms that already exist.

Thanks

**Comment by toolstack** [comment]
I don't think it's worth going back to try and detect existing 'broken' glossary terms programatically, they don't break anything per say and if someone edits one it will give the error.

**Comment by garretthyder** [comment]
Sounds good, you're right is probably more work than it's worth to test the existing. So just an error on submission would suffice

**Comment by ocean90** [comment]
I don't think we should block them, why not removing such characters automatically? Sounds also like a rare case since we request a _term_ and not a _sentence_.

**Comment by toolstack** [comment]
Agree it's a rare case, blocking seemed safer as you might get strange cases where simply removing them would not be good (typos for example).

The block and error makes sure it gets some attention, a simple replace might create unwanted entries.

Also, doing a bit of research seemed to show `\b` was very implementation dependent.
