### ISSUE TITLE
Avoid flashing in filters toolbar caused by select box for bulk priority

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#775]
![kapture 2017-07-02 at 16 09 18](https://user-images.githubusercontent.com/617637/27770557-dc0cf4ee-5f40-11e7-9184-db978a3d9d99.gif)

**Comment by toolstack** [comment]
I haven't been able to reproduce this, where is the cursor when the flashing happens?

**Comment by ocean90** [comment]
It's not related to the cursor. [This line](https://github.com/GlotPress/GlotPress-WP/commit/2ed5bf4b5dd37679c7201b4f9a1fe5ab73dab518#diff-43550da8e7ca0c083ef73b8693215953L15) is called once the document is ready which means the select will be displayed until the event kicks in.

**Comment by toolstack** [comment]
Got it, it doesn't flash in Firefox on Windows but does in Chromium, but so fast it's hardly visible.
