### ISSUE TITLE
Submitting Translation w/ Glossary Term highlight and reopening row loses highlight

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#778]
Hello,

Just wanted to flag a minor issue with Glossary Term highlighting. It seems when you submit a translation on a row that contains a Glossary Term that it loses it's highlighting so when you open the translated row the Glossary Term(s) are no longer underlined/highlighted.

Cheers

**Comment by ocean90** [comment]
How is that different from #704?

**Comment by garretthyder** [comment]
Sorry @ocean90 you're right. They're the same underlying issue it appears, was just how I produced them that was different; #704 I noticed after a reject, this one I noticed after a submission but I guess same action/issue. Closing
