### ISSUE TITLE
String containing two of the same Glossary Term doesn't highlight/underline the second one

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#779]
Hello,

Just wanted to flag that if a string contains two of the same terms the second one doesn't get highlighted/underlined;
![screen shot 2017-07-05 at 10 47 19 am](https://user-images.githubusercontent.com/8726005/27877446-7fa2e87c-616f-11e7-9d9b-79d69cfe1479.png)
Permalink - https://translate.wordpress.org/projects/wp-plugins/wp-photo-album-plus/dev/en-ca/default?filters%5Boriginal_id%5D=4759331

Not sure if it has anything to do with the first term being a variant with suffix.

Cheers

**Comment by toolstack** [comment]
This is caused by the fact that we use `preg_match()` instead of `preg_match_all()` when [looking](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-templates/helper-functions.php#L110) for glossary terms, so only the first variant is matched.
