### ISSUE TITLE
Missing tooltips for glossary terms

### ISSUE THREAD

**Issue by Mte90** [GlotPress/GlotPress-WP#781]
Take this one as example: https://translate.wordpress.org/projects/wp-plugins/my-calendar/dev/it/default?filters[status]=either&filters[original_id]=915341&filters[translation_id]=24842364

Default for italian as a glossary term, Predefinito as we can see on https://translate.wordpress.org/locale/it/default/glossary

I was trying to understand how few tooltips add glotpress on terms, glotdict didn't have this kind of problem with the same terms.
Maybe is a bug on search terms inside glotpress?

**Comment by toolstack** [comment]
This one is because glossary terms were matched case sensitive until #703, which will be included in the next GP release.

**Comment by Mte90** [comment]
Wow ok there is an eta for this feature on translate.wp.org? I think that is very important.

**Comment by toolstack** [comment]
No hard date at this time, it's on the agenda for the next GP meeting (the next release that is, not implementation on translate.w.org).
