### ISSUE TITLE
Standalone URL should match Glossary Term but isn't highlighted

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#782]
Hello,

I'm pretty sure this is unique as it's not a case-sensitive issue or multiple in string, but when a URL (https://wordpress.org/) is the only text in a string and is a Glossary Term is should match/underline but isn't.
Permalink - https://translate.wordpress.org/projects/wp-plugins/better-wp-security/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4765341&filters%5Btranslation_id%5D=50488261

Glossary - https://translate.wordpress.org/locale/en-ca/default/glossary

Cheers

**Comment by toolstack** [comment]
That would be because `.` (and maybe `/` and `:`) would be a word delimiter and so the matching would be on `wordpress` and not the full url.

Glossaries only handle words, not phrases, sentences or other things with word breaks in them.

**Comment by garretthyder** [comment]
Thanks @toolstack was definitely the trailing slash /, seems it only occurred when it was the final character in the string. If found anywhere else within a string was highlighting without issue.
To resolve for en_CA I simply dropped the trailing slash.
It's odd that it would detect it when within a string but not when at the end of a string.

**Comment by toolstack** [comment]
That's the black magic of the regular expressions at work :wink:
