### ISSUE TITLE
URL Changed Warning only picks up first instance

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#783]
Hello,

When you modify a URL to localize it you get a warning about the URL change, if the string contains two URLs and both get changed only the first is noted. Would be nice to list all changed URLs within the warning.

Permalink - https://translate.wordpress.org/projects/wp-plugins/debug-bar-elasticpress/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=2123607&filters%5Btranslation_id%5D=50489390

Thanks

**Comment by toolstack** [comment]
As mentioned in #728, the URL warnings are part of translate.w.org, not GlotPress.

**Comment by ocean90** [comment]
Related: #370

**Comment by garretthyder** [comment]
Thank you
