### ISSUE TITLE
Changed URL doesn't trigger warning

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#785]
Hello,

When I went to translate a string containing '(https://wordpress.org/plugins/debug-bar/)' and localized it to '(https://en-ca.wordpress.org/plugins/debug-bar/)' I was expecting the URL change warning but didn't receive anything. Is the regex ignoring it because it's surrounded in parentheses?

Permalink - https://translate.wordpress.org/projects/wp-plugins/debug-bar-screen-info/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=1720714&filters%5Btranslation_id%5D=50534103

Thanks

**Comment by toolstack** [comment]
As mentioned before (see #783) , URL warnings are part of translate.w.org, not GlotPress

**Comment by SergeyBiryukov** [comment]
> I was expecting the URL change warning but didn't receive anything.

That's intentional, WordPress.org links are [allowed to be changed to a subdomain](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-gp-custom-warnings/wporg-gp-custom-warnings.php?rev=3390#L13).

**Comment by garretthyder** [comment]
Thanks @toolstack I'll move this into translate.w.org

@SergeyBiryukov I appreciate the information, I tested a couple as I definitely recalled seeing the warning on a few occassions and found that when the URL is standalone or within parentheses () no warning is triggered. However if the URL is within a link element it does trigger a warning;
![screen shot 2017-07-11 at 9 19 57 am](https://user-images.githubusercontent.com/8726005/28078638-69ccccfc-661a-11e7-9eba-3c189cb70c26.png)
Permalink - https://translate.wordpress.org/projects/wp-plugins/debug-bar-constants/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=1668546&filters%5Btranslation_id%5D=50545119

I've opened this on meta trac here;
https://meta.trac.wordpress.org/ticket/2949

Thank you
