### ISSUE TITLE
show count of all submitted translations in statistics...

### ISSUE THREAD

**Issue by qdinar** [GlotPress/GlotPress-WP#786]
see for example

https://translate.wordpress.org/locale/tt/default/wp/dev

i am "Dinar Qurbanov" there and have 1786 translations and  "Kazan Federal University" has 131 translations. but really Kazan Federal University has submitted more than 131 translations, but i have edited some of them. even if i make little changes and more of work on a string is done by other user, it is accounted as mine translation in the statistics, when i edit and accept translation, so i thought that statistics are not very fair.

**Comment by ocean90** [comment]
The statistics are not part of GlotPress core, it's a feature specific to https://translate.wordpress.org.

**Comment by qdinar** [comment]
https://meta.trac.wordpress.org/ticket/2961#ticket
