### ISSUE TITLE
Wrong behaviour on adding tooltips on path inside text

### ISSUE THREAD

**Issue by Mte90** [GlotPress/GlotPress-WP#787]
The bug was reported on GlotDict https://github.com/Mte90/GlotDict/issues/98 but is a bug of GP that add tooltips on string inside a path.

**Comment by ocean90** [comment]
Thanks for the report. That sounds like an edge case me. Fixing this would probably to much work for the minimal benefit because who should know whether `/this/too` or `not/this` is a path or not.

Closing as wontfix for now.
