### ISSUE TITLE
Add option to see "rejected" and "old" strings, with current

### ISSUE THREAD

**Issue by xavivars** [GlotPress/GlotPress-WP#789]
When coaching new translators, it's very important to show what are the old/rejected strings, and the ones that have been added instead.

The following link helps, by showing both rejected and old strings. But then is really hard to find the ones that have replaced each of them.

`https://translate.wordpress.org/projects/wp-plugins/PLUGIN_NAME/dev/LANGUAGE/default?filters%5Bterm%5D&filters%5Buser_login%5D=USERNAME&filters%5Bstatus%5D=old_or_rejected&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc&page=1`

Would it be possible to have a filter (or an export) that had a three-column view with "Original string" "rejected string" "current translation"?

**Comment by ocean90** [comment]
Sounds like an interesting idea but this some more work first. We should try to avoid printing the same translations multiple times so a table might not be the best idea here. Needs some design work to catch all the possible cases (including plurals).

Related chat: https://wordpress.slack.com/archives/C02RP4R9F/p1502817504000565

**Comment by La-Geek** [comment]
I don't know how far this has evolved. Just a short idea, how about inserting short linked references to existing translations? Like:  rejected 2, waiting 0, fuzzy 1

**Comment by ocean90** [comment]
This was added in #360.
