### ISSUE TITLE
Filter 'Without current translation' doesn't seem to work as expected

### ISSUE THREAD

**Issue by tacoverdo** [GlotPress/GlotPress-WP#790]
# Problem description
The Dutch translation of a plugin has 42 untranslated strings, as you can see in the screenshot below.
![development__trunk____glotpress_ _wordpress](https://user-images.githubusercontent.com/5147598/28924862-64c75604-7863-11e7-9feb-334e551fb503.png)

Of course, I want to translate those 42 first, before I start working on all the improvements that have been suggested. That's why I go to the list of strings and set the filter to only show 'Without current translation'. What I expect is that I now see the 42 untranslated strings.
![translations___dutch___development__trunk____glotpress_ _wordpress](https://user-images.githubusercontent.com/5147598/28925247-93f0545c-7864-11e7-8b7a-dd197a529fd1.png)

Unfortunately, no translations were found.
![translations___dutch___development__trunk____glotpress_ _wordpress](https://user-images.githubusercontent.com/5147598/28925278-b1098360-7864-11e7-8548-d9b3a6e3609a.png)

# Possible solution
Exclude waiting strings when filtering for items without *current* translation. This would also be in line with the legend.
![translations___dutch___development__trunk____glotpress_ _wordpress](https://user-images.githubusercontent.com/5147598/28925378-02151666-7865-11e7-9445-5b3132cd7751.png)

# Additional information
This problem occurred on translate.wordpress.org and https://translate.yoast.com.

**Comment by toolstack** [comment]
I can't reproduce this, could you provide the link to the translate.w.org project you see this behaviour in?

**Comment by ocean90** [comment]
Notes for today's office hours:
* The project is https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/dev
* https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/dev/fr/default?filters%5Bterm%5D=&filters%5Buser_login%5D=&filters%5Bstatus%5D=untranslated&filter=Filter&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=desc
* See also https://github.com/GlotPress/GlotPress-WP/blob/7fda1387cfd1d10c2443ec1daf54625385d509ea/gp-includes/things/translation-set.php#L500

**Comment by toolstack** [comment]
Example: https://translate.wordpress.org/projects/wp-plugins/wordpress-seo/dev/fr/default?filters%5Bterm%5D=&filters%5Buser_login%5D=&filters%5Bstatus%5D=untranslated&filter=Filter&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=desc

Summary says 14 strings, locale only has 4.

**Comment by toolstack** [comment]
TODO note in code here: https://github.com/GlotPress/GlotPress-WP/blob/7fda1387cfd1d10c2443ec1daf54625385d509ea/gp-includes/things/translation-set.php#L500
