### ISSUE TITLE
Question: What about the standalone version?

### ISSUE THREAD

**Issue by sandebert** [GlotPress/GlotPress-WP#814]
Hi all,

Quoting from [the WP plugin page](https://wordpress.org/plugins/glotpress/):

_GlotPress has two versions, a standalone version and this WordPress plugin version. At this time these two versions are functionally similar, but the plugin version is likely to start moving away from the standalone version in future versions._

I haven't been able to find any other information about the standalone version anywhere. How do I install it? Requirements? Download url?

Also, does this in effect mean that the standalone version will cease to exist as all effort is poured into the WP plugin version?

(Just to be clear: I have no interest in installing WP just to use GP.)

**Comment by swissspidy** [comment]
You can find the standalone version over at https://github.com/GlotPress/GlotPress, however, all efforts are put into the WordPress plugin version as the standalone one isn't supported or maintained anymore.

**Comment by sandebert** [comment]
Thanks.

It might be a good idea to update that page, and the WP plugin page, to clarify that the standalone is not maintained anymore.

**Comment by toolstack** [comment]
The standalone version is now officially retired, the plugin is the only version of GlotPress now.

We'll make sure to update the readme for the next release, thanks for pointing it out.
