### ISSUE TITLE
Travis does supports PHP 5.3 on Trusty

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress-WP#817]
We can either force it to use percise as per the [docs](https://docs.travis-ci.com/user/reference/trusty#PHP-images) or remove 5.3 from the testing.

**Comment by Mte90** [comment]
Probably remove PHP 5.3 support that now have a low user base

**Comment by toolstack** [comment]
I'd be fine with that as well, in fact I'd think that at this point 5.6 would probably be a reasonable minimum, at least it still has [security patches](http://php.net/supported-versions.php) for another ~year.

**Comment by ocean90** [comment]
Related #572

I wouldn't mind using 3.0 also to bump the minimum supported PHP version to 5.6.

**Comment by toolstack** [comment]
That sounds like a plan, I'll create a new PR to drop the older versions from Travis and update the minimum version `define()`.

**Comment by toolstack** [comment]
Closed with the merge of #819.
