### ISSUE TITLE
Add parameter wp_locale for zh_SG

### ISSUE THREAD

**Issue by tobifjellner** [GlotPress/GlotPress-WP#823]
Chinese (Singapore) zh_SG has been requested for activation on translate-wordpress-org.
Request URL: https://make.wordpress.org/polyglots/2017/07/13/chinese-singapore-gte-request/

Therefore, we need to add the parameter wp_locale for this locale.

Previous description:
When I tried to search for zh_SG at https://translate.wordpress.org/ I got no match.
The reason seems to be that the parameter wp_locale is undefined and therefore defaults to the slug value.

Currently, three locales are presented with hyphen (-) rather than underscore. They are:
el-po
zh-sg
fr-ch

**Comment by tobifjellner** [comment]
For the moment, we'll only update zh_SG.

**Comment by toolstack** [comment]
Not all locales have `wp_locale` properties and I expect that will become more common in the future with CLDR support.

I believe the polyglot's team usually chooses the value for them when they are added.

**Comment by tobifjellner** [comment]
In a comment on Slack, @ocean90 commented that this parameter is added when a locale gets activated on translate.wordpress.org.
We've got a request for zh_SG now, so that locale will be updated. (And several other domains are about to be added, too.)

**Comment by toolstack** [comment]
That's one of the slightly weird interactions between GP and translate.w.org, as GP doesn't actually use the parameter.

**Comment by tobifjellner** [comment]
Issue description has been updated:
Chinese (Singapore) zh_SG has been requested for activation on translate-wordpress-org.
Request URL: https://make.wordpress.org/polyglots/2017/07/13/chinese-singapore-gte-request/

Therefore, we need to add the parameter wp_locale for this locale.
