### ISSUE TITLE
Rename "Branch Project" and other "branch" related strings

### ISSUE THREAD

**Issue by pedro-mendonca** [GlotPress/GlotPress-WP#825]
The term _branch_ is mostly related with translate.wp.org itself and general repository branches.
In GlotPress the _branches_ are generically called sub-projects, as they can have a multi-level hierarchy.

The *Branch Project* and other _branch_ related strings are about cloning, forking a project in GlotPress.

A better naming could be *Clone Project*, *Duplicate Project* or *Copy Project*.

**Comment by Mte90** [comment]
So probably we need a map of this strings so we can evaluate the better naming

**Comment by pedro-mendonca** [comment]
## List of occurrences

**`Branch project`**
- [Link to _branch_ creation page](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-includes/template.php#L513)
- [Button to create _branch_](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-templates/project-branch.php#L33)

**`Branch project "%s"`**
- [Heading of _branch_ creation page](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-templates/project-branch.php#L6)

**`Branch project "%s" &lt; GlotPress`**
- [Page title of _branch_ creation page](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-templates/project-branch.php#L2)

**`Here you can branch out this project: everything will be duplicated into a new project for you.`**
- [Description of _branch_ creation page](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-templates/project-branch.php#L7)

**`New branch name`**
- [Label of name input field in _branch_ creation page](https://github.com/GlotPress/GlotPress-WP/blob/develop/gp-templates/project-branch.php#L9)

**Comment by Mte90** [comment]
Uhm the labels are only in 2 files so maybe is better to use Duplicate or Clone everywhere and in the page of Branch change also the explanation (in case if needed).

I think that Duplicate is better because usually when someone duplicate is to start from something that already exist to alter it more quickly instead of clone that sometimes is something to update the parent project.

**Comment by pedro-mendonca** [comment]
I agree @Mte90 
Duplicate is a good choice.
Also, being a _branch_ wouldn't allow a sub-project to move around in the hierarchy, choosing another *parent* or moving it to the root.

The description **`Here you can branch out this project: everything will be duplicated into a new project for you.`** is quite clear and correct, and it's about making a duplicate at some point.

**Comment by pedro-mendonca** [comment]
@Mte90 feel free to comment and suggest changes to the above mentioned PR https://github.com/GlotPress/GlotPress-WP/pull/826

**Comment by ocean90** [comment]
GlotPress is a tool to translate software so branching sounds totally fine to me. I don't see the need for changing UI strings here since the code is still about "branching".

**Comment by pedro-mendonca** [comment]
Don't you think a _branch_ is somehow permantly related to its origin/superior?
The GotPress sub-projects can be moved around in the hierarchy structure, and after being _branched_, keep no relation with its origin.

**Comment by toolstack** [comment]
I don't see a lot of benefit to changing the terminology in this case, branching doesn't always have a relationship back to the original (ie. git) and changing it now would only confuse things.

I'm leaning towards closing this as a ```wontfix``` unless someone can provide a more tangible benefit to changing it.

**Comment by ocean90** [comment]
Closing as _wontfix_ based on above discussion.
