### ISSUE TITLE
Español de Costa Rica is missing part of label

### ISSUE THREAD

**Issue by GaryJones** [GlotPress/GlotPress-WP#836]
`wp_get_available_translations()` in WP Core shows "Español" as the native name for both `es_CR` (Costa Rica) and `es_ES`. This is only possible to see by looking at the markup. I believe that the first should be something like "Español de Costa Rica" (or whatever the suitably localised version would be).

https://github.com/GlotPress/GlotPress-WP/blob/a278bb001d99bc96c2e21e20002958a7c7d3d222/locales/locales.php#L693

![espanol-label-missing](https://user-images.githubusercontent.com/88371/31122413-9fc5c434-a833-11e7-974d-ad8b5976f286.png)

**Comment by tobifjellner** [comment]
At the same time I´ll use the opportunity to add 639-3 labels for all Spanish locales.
Question: Would we break anything if you at the same time change the locale code es_CR to es_cr?
