### ISSUE TITLE
Change internal code sq_XK to all lowercase

### ISSUE THREAD

**Issue by tobifjellner** [GlotPress/GlotPress-WP#843]
All letters in GlotPress internal locale codes are now, lowercase, except for sq_XK Shqip (Kosovo)
This code, too, should be changed to all lowercase.

**Comment by tobifjellner** [comment]
At the same time, we can add iso 639-2 and iso 639-3 code = sqi

**Comment by ocean90** [comment]
sqi is only for https://github.com/GlotPress/GlotPress-WP/blob/504446cb16ab6a65fe87ed16f6cb6f7689359876/locales/locales.php#L1836-L1845
