### ISSUE TITLE
Patch scope comparing against master instead of dev

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress-WP#846]
Something has changed in the dev-lib that is comparing PR's against master instead of develop, the fix is to add `DIFF_BASE=develop` to the TravisCI build environment.

**Comment by ocean90** [comment]
Looks like it's this change https://github.com/xwp/wp-dev-lib/commit/fd0b392c8b5e0867010965cac769d69744a36ccb

Instead of `DIFF_BASE` it's `GITHUB_DEFAULT_BRANCH`.

**Comment by ocean90** [comment]
Hmm, looks like it got renamed to `DEFAULT_BASE_BRANCH`, see https://github.com/xwp/wp-dev-lib/commit/3620031de79f69ad0475c6d989f48733693d1eab.
