### ISSUE TITLE
The plugin is not working on my sites

### ISSUE THREAD

**Issue by iagobruno** [GlotPress/GlotPress-WP#854]
I installed the plugin on 2 different sites (one location and the other hosted) and even then I can not use the plugin through url **<home_url>/glotpress/** as [explained in the official website](https://glotpress.blog/the-manual/installation/) and there is nowhere in the panel the name "GlotPress" with a link.
Do I have to do any configuration for the plugin to work?

**Comment by toolstack** [comment]
Do you have pretty permalinks enabled on your site (they're required for GP)?

If you go to the WP plugins page are there any warning messages at the top related to GP?
