### ISSUE TITLE
Add warning if the interpunctation differs

### ISSUE THREAD

**Issue by Zodiac1978** [GlotPress/GlotPress-WP#859]
For example: If the the original strings ends with a period a the translation not, add a warning.

PoEdit does that too.

**Comment by toolstack** [comment]
This would only work for English like languages that have similar punctuation.  Not something that would be very useful for languages like Japanese or Chinese.  Not something I would be in favour of including in core.

**Comment by Zodiac1978** [comment]
Opt-out for Japanese/Chinese is not an option? How many languages have those different punctuation?

**Comment by toolstack** [comment]
Lots of languages have different punctuation rules, trying to track which ones are or are not supported seems like a lot of work for little actual benefit.

**Comment by Zodiac1978** [comment]
But if this is just comparing original string and translation this wouldn't be necessary, because the Japanese/Chinese original string wouldn't have any period at the end. It would be a warning like a missing placeholder or a link which is different in the translation ...

**Comment by toolstack** [comment]
Unlike missing placeholders or link differences, this would effect an order or magnitude more strings, as for non-english languages a large percentage would be flagged incorrectly with the warning.

**Comment by Zodiac1978** [comment]
I still don't get why this should happen. If the original string does not end with a period the translation shouldn't end with a period (for example). This should work in all languages and without any false positives. Or am I missing something?

**Comment by toolstack** [comment]
Your missing something... it's not that both don't have interpunctation, it's that the original does and the translation doesn't.

For example if the original is:

```This is a test.```

 Then the Japanese translation might be:

```これはテストです。``` 

There's no period at the end of that string (well, at least nothing that looks like a period from the original at least).  Non english-like languages may have significantly different punctuation rules (or just completely lack punctuation).  For example see the [Wikipideia article on Japanese punctuation](https://en.wikipedia.org/wiki/Japanese_punctuation).

This would cause virtually any translation with a punctuation mark to get incorrectly flagged with a warning.

**Comment by toolstack** [comment]
Closing as won't fix.
