### ISSUE TITLE
Add a flag to show that a string has a history of translations (or hide link if not) 

### ISSUE THREAD

**Issue by Zodiac1978** [GlotPress/GlotPress-WP#862]
If a translation editor is approving strings he/she have to check the "All translations of this string" link all the time, to see if there are more translations of the same strings waiting. Even if there are no translation.

We could show all translations on that page (so I don't have to click the link) and hide the link completely if it would show "no translations".

First reported in these two tickets:
https://glotpress.trac.wordpress.org/ticket/228
https://glotpress.trac.wordpress.org/ticket/338

**Comment by toolstack** [comment]
Related to #623.

**Comment by Zodiac1978** [comment]
I missed #623 - we could close this one or do you think this one adds an additional thought that should be thought of?

**Comment by toolstack** [comment]
I would tend to close it as the performance hit of loading "all translations" for each string on the page could be significant.

**Comment by Zodiac1978** [comment]
I don't know what you mean, because these two tickets have **exactly** the same goal. We can close this one here, because #621 is referencing the same old tickets:
https://glotpress.trac.wordpress.org/ticket/228
https://glotpress.trac.wordpress.org/ticket/338
And they have the same goal.
