### ISSUE TITLE
Highlight trailing spaces

### ISSUE THREAD

**Issue by Zodiac1978** [GlotPress/GlotPress-WP#863]
PoEdit highlights the space if it is (non-visible) after the end of the text:

![bildschirmfoto 2015-10-19 um 11 09 17](https://user-images.githubusercontent.com/870475/34906254-04945b7e-f86a-11e7-95c4-d5b74f7b32c6.png)

If this is not working technically. We could add an warning in this case (if we don't do this already).

Related: https://github.com/GlotPress/GlotPress-WP/issues/801

**Comment by itssimple** [comment]
Yeah, I'd like to see if the actual phrase has trailing spaces too. But regarding the styling, normal textareas can't handle that, but there are other editors that could handle this.

**Comment by Mte90** [comment]
Glotdict support that :-)

**Comment by audrasjb** [comment]
Hi,
I'll kindly disagree @Mte90 :)
GlotDict supports non-breaking spaces visibility as seen in https://github.com/GlotPress/GlotPress-WP/issues/801 but we dont support strings ending up with a classic space char. I Guess this is a real issue for GlotPress, not for GloDict. I can work on a patch this week if you confirm my opinion about this issue :)

**Comment by Mte90** [comment]
You are right and the boss about that is you :-)

**Comment by audrasjb** [comment]
Great, lets roll then :)

**Comment by audrasjb** [comment]
@Zodiac1978 please can you give me a link to an example string?

**Comment by audrasjb** [comment]
@Mte90 I'm sorry I said nonsense. I was wrong because this is strongly Glotdict related 😝  
We dont have to highlight chars in the textarea. We can highlight them in the preview and add a warning if an ending space is missing on validation. I will move my work into Glotdict repo ^^

**Comment by ocean90** [comment]
Also mentioned in #166.

**Comment by audrasjb** [comment]
Hi,
This issue is referenced (and can be partially fixed) in this PR on GlotDict: https://github.com/Mte90/GlotDict/pull/129

Cheers,
Jb
