### ISSUE TITLE
Do not allow partly empty singular/plural translations 

### ISSUE THREAD

**Issue by Zodiac1978** [GlotPress/GlotPress-WP#864]
If you have a string which has Singular and Plural and you have just translated the Singular or the plural of the string, the whole string is marked as translated (green).

It should remain untranslated until the second part is translated too.

First reported here: https://glotpress.trac.wordpress.org/ticket/149

I'm not sure if this is still the case ... but I think yes, so I leave it here. If someone knows better, please close or confirm. Thank you! :)

**Comment by toolstack** [comment]
This was fixed in a previous release, you can no longer save a plural translation without filling in all plurals for it.
