### ISSUE TITLE
Fuzzied strings that are also waiting cause confusion

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#866]
Hello,

Not sure if this is expected behaviour, but if a plugin update causes a string to become fuzzy and then someone supplies a waiting string for it then both versions are available through their respective filters (Fuzzy and Waiting). If you attempt to update the Fuzzy version you get blocked because there's an existing waiting string. At first I didn't realize there was the Waiting string so thought I was just blocked. I found I had to go approve the waiting string and then both the Waiting and Fuzzy get resolved. In my mind if there's a waiting string the fuzzy shouldn't be there anymore or you get two active strings and get blocked when using the Fuzzy version.

Example of this.
There's two fuzzy strings here;
https://translate.wordpress.org/projects/wp-plugins/dismiss-gutenberg-nag/dev-readme/en-ca/default?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=fuzzy
If you copy original and submit you get the notice 'Error: Identical current or waiting translation already exists'
So you have to go and find the Waiting version and approve/reject it. If you approve then the fuzzy vanishes, and if you reject then you can go to the fuzzy and use it to push the update.

Screen of this;
![screen shot 2018-01-15 at 11 24 02 am](https://user-images.githubusercontent.com/8726005/34958390-9aeab2c6-f9e6-11e7-82c8-b04a72c0738d.png)

If this is expected no worries. Just found it confusing at first why I couldn't submit a fix to the Fuzzied string.

Thanks

**Comment by toolstack** [comment]
Yes this is expected behaviour, perhaps though not the best UX.

**Comment by garretthyder** [comment]
Thanks @toolstack I wonder if the data about there being a waiting string is available to the fuzzy row, in which case it would be nice to disclose that in the meta so users are aware they should look at the waiting string instead of the fuzzy one. Maybe something as simple as adding into the 'Status'
![screen shot 2018-10-02 at 2 48 36 pm](https://user-images.githubusercontent.com/8726005/46379008-4f02c680-c652-11e8-9f18-7f06f4a76863.png)

**Comment by toolstack** [comment]
As I recall it's not directly available at that time, it would require another query to the database.

**Comment by garretthyder** [comment]
Thanks @toolstack I wonder if running that additional query to find all related translations would not only be useful in this case but also for #902 and could surface the information about this item having other variants to translators to assist them?

**Comment by toolstack** [comment]
Yes, it would be required for #902 as well so it may make sense to handle as part of that ticket.

**Comment by garretthyder** [comment]
Thanks @toolstack added a related there
