### ISSUE TITLE
“Case insensitive” filter currently only works for English

### ISSUE THREAD

**Issue by tobifjellner** [GlotPress/GlotPress-WP#867]
If you try to use the filter function to find some strings and leave the option "Case sensitive" unchecked, then search still is case sensitive for those letters in the Swedish alphabet that aren't present in the English alphabet (Specifically åäö – ÅÄÖ).
Most probably the filter function for "case insensitive" ought to be expanded to work correctly for at least some languages.
In addition, a disclaimer tooltip could be added next to the filter option, mentioning that non-English characters may still remain case sensitive.

**Comment by ocean90** [comment]
What database character set and collation are you using?

**Comment by tobifjellner** [comment]
Whatever is used on translate.wordpress.org

**Comment by tobifjellner** [comment]
Got. So this is simply a parameter for the query, and the result depends on the settings in your database. Then perhaps some kind of "warning" might be relevant.

**Comment by ocean90** [comment]
https://meta.trac.wordpress.org/ticket/1063
