### ISSUE TITLE
Very long words in strings are breaking UI

### ISSUE THREAD

**Issue by audrasjb** [GlotPress/GlotPress-WP#875]
Hello,

A french team contributor noticed very long words can break GlotPress UI.

Example: https://translate.wordpress.org/projects/wp-plugins/duplicate-page/stable-readme/fr/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5633108&filters%5Btranslation_id%5D=53864572

![capture d ecran 2018-02-13 a 22 56 18](https://user-images.githubusercontent.com/1590998/36176068-bc7138e2-1111-11e8-93de-70297b1fc7d9.png)

A small patch will follow this issue.

Cheers,
Jb

**Comment by fr-laurentn** [comment]
@audrasjb Thanks for reporting the issue.

Actually, the issue I noticed was when the editor is closed.
So it seems that you only fixed part of the issue.

Example:
![bug_glotpress](https://user-images.githubusercontent.com/15927630/36204089-27c45aa2-118a-11e8-9fcf-0a8d354ec342.png)

If you look at the CSS, there's an invalid property:
```
table.translations td.original, table.translations td.translation {
    width: 45%;
    word-break: break-word;
    word-wrap: break-word;
}
```

If you replace  `word-break: break-word;` with  `word-break: break-all` it seems to fix it.

**Comment by toolstack** [comment]
There are a few places long words break the display of the wrapping (including in context strings as well), I think I've caught them all in #877.
