### ISSUE TITLE
When a translation is marked Fuzzy, you cannot find it

### ISSUE THREAD

**Issue by davidperezgar** [GlotPress/GlotPress-WP#881]
Hello, 
I did find that when a translation in marked fuzzy, you cannot find it in the filters, and it should be in the  Untranslated filter, becouse that translation won't be definitive until you approbe it.

Regards.

**Comment by Mte90** [comment]
An example link to test and replicate the issue?

**Comment by toolstack** [comment]
I can reproduce this, though I'd say that it shouldn't be in the "Untranslated" filter, but that we're missing a "Fuzzy" filter instead.

**Comment by ocean90** [comment]
The filter is already there, only hidden for regular translators. #886 makes them visible to everyone.

**Comment by Mte90** [comment]
So we have to wait for the approval of #886?

**Comment by davidperezgar** [comment]
It should be nice to have it for regular translators, becouse we could use it to contribute for translation...

**Comment by Mte90** [comment]
The next version will have this feature as written by dominik :-)

**Comment by davidperezgar** [comment]
Nice!
