### ISSUE TITLE
Error shows up for a second when saving, but saving still works

### ISSUE THREAD

**Issue by Presskopp** [GlotPress/GlotPress-WP#888]
![glotpress-error](https://user-images.githubusercontent.com/18373563/38777852-28ad4894-40af-11e8-8e61-b79f655fe8e1.gif)

Let me know if more details are needed

**Comment by ocean90** [comment]
Can you reproduce this with all browser extensions disabled? What's the link to the project? What browser are you using?

**Comment by Presskopp** [comment]
You're right, it's the browser extensions. The funny thing is, I disabled them all, enabled them one by one and now the issue is gone. I thought it could be Glotdict causing it and disabled only this one before. This happens on chrome. So feel free to close the issue as resolved.
