### ISSUE TITLE
Enhancement: Display if a project has translation validators in the editors waiting projects page

### ISSUE THREAD

**Issue by lenasterg** [GlotPress/GlotPress-WP#890]
Hi. 
It would be useful for the locale's traslation editors if the waiting projects page had a mark for the project which have translation editors. 
Something like the https://ibb.co/mU7obn draft screenshot.

**Comment by ocean90** [comment]
Since this is a specific request for translate.w.org it needs to be requested on https://meta.trac.wordpress.org/newticket?component=Translate+Site+%26+Plugins&type=enhancement.

**Comment by lenasterg** [comment]
@ocean90 , thanks for the heads up. I open the request there.
