### ISSUE TITLE
Slug of Pirate locale doesn't fit into `locale` column size

### ISSUE THREAD

**Issue by ocean90** [GlotPress/GlotPress-WP#891]
The `locale` column of the translation set only allows 10 characters. Pirate has 11 with `art-xpirate` so it only gets stored as `art-xpirat`.

Two options: Increase column size of `locale` field or change the `slug`  property of the `GP_Locale` to something shorter like `pirate`.

**Comment by danieltj27** [comment]
Ah it was automatically referenced above, that's handy.

In PR #894 I've changed the code and slug to remove `art` from it so it's sorter. It may be worth making the column longer in the long run, but considering most locales don't stray away from roughly four letter codes, it seems a bit more work to increase the column size.

It still uses `xx` as a prefix to denote the nature of the locale.
