### ISSUE TITLE
Word wrapping makes translation strings difficult to read

### ISSUE THREAD

**Issue by danieltj27** [GlotPress/GlotPress-WP#892]
In PR #882 word wrapping was adding to ensure that long words didn't break the UI, but I've found since this change, every word is being broken making strings very difficult to read.

For example:

![Uploading glotpress-translation-string-break.png…](https://user-images.githubusercontent.com/8491069/39418702-d043d69a-4c53-11e8-8725-bd1c426d2c91.png)

It's even breaking up small words. A better fix needs to be in place to ensure this wraps words instead of breaking them as that makes reading very difficult for the end user.

**Comment by Presskopp** [comment]
This is indeed disturbing, @danieltj27 , don't you have a patch?

**Comment by danieltj27** [comment]
No, I haven't had the time to look into a word-around for this. If I do, I'll try and submit something but for now it's open to anyone that'd like to.

**Comment by Mte90** [comment]
We wasusing `break-word` and now is `break-all` https://developer.mozilla.org/en-US/docs/Web/CSS/word-break so maybe we need a more advanced solution.

**Comment by garretthyder** [comment]
I just ran into this myself and found it harder to validate translations as each columns breaks differently so sometimes you feel there's a difference when there isn't;
<img width="954" alt="screen shot 2018-04-30 at 12 04 19 pm" src="https://user-images.githubusercontent.com/8726005/39445285-7067e9b6-4c6f-11e8-83b4-312bc447f498.png">
*In this screen I thought memory was broken on the right, but the m was just on a previous line.

I pulled up the original ticket for the break-all change;
https://github.com/GlotPress/GlotPress-WP/issues/875

Testing with that example and the ones I have lead me to using `word-break: break-word;` as an all-encompassing fix here as it breaks the line at words where it can unless it's a massive string and only then breaks the actual word.

PR coming

**Comment by ocean90** [comment]
See https://meta.trac.wordpress.org/changeset/7180 for what I'm testing on translate.w.org to solve this.

https://translate.wordpress.org/projects/wp/dev/en-gb/default?filters%5Bterm%5D=tain&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc is a good example with the string for `wptexturize()`.

**Comment by garretthyder** [comment]
Nice @ocean90 
That seems to be a better cross-browser fix from my testing so far. I'd played with the `overflow-wrap: break-word` before but it looks like I just needed the `table-layout: fixed` on the table itself for columns to adhere to the width settings.
Nicely done, tested Chrome, Firefox and Opera with success
But sadly testing on Safari and Edge I found text didn't break and would overflow;
Edge 13
![screen shot 2018-05-04 at 2 52 10 pm](https://user-images.githubusercontent.com/8726005/39654687-c43f6b98-4faa-11e8-99ec-989a175cb008.png)
Safari
![screen shot 2018-05-04 at 2 49 01 pm](https://user-images.githubusercontent.com/8726005/39654692-cac72e9c-4faa-11e8-92d6-f96c06110a0c.png)

**Comment by ocean90** [comment]
@garrett-eclipse Thanks for testing, updated in https://meta.trac.wordpress.org/changeset/7182.

**Comment by garretthyder** [comment]
By George, I think you've got it ;)

Testing this link;
> https://translate.wordpress.org/projects/wp/dev/en-gb/default?filters%5Bterm%5D=tain&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

I tested Safari, Opera, Chrome, Edge, Firefox successfully, that's not to say older browsers might have issues but with all the latest you're looking good.

Cheers

**Comment by garretthyder** [comment]
Hey @ocean90 
Coming back to this as I was translating a bit this morning and found when you open a row the current translation has the wrap on small words, not sure if that can be addressed with the same fix you put for other places.
![screen shot 2018-05-14 at 10 04 52 am](https://user-images.githubusercontent.com/8726005/40012072-6d771ac0-575e-11e8-917f-6410aa963d09.png)

The selector seems to be `.editor .translation` or `.gp-content blockquote`

Cheers

**Comment by ocean90** [comment]
Updated in https://meta.trac.wordpress.org/changeset/7205.

**Comment by garretthyder** [comment]
Thanks @ocean90 it's looking pretty good there ran it through Safari, Opera, Chrome, Edge, Firefox successfully. Cheers

**Comment by ocean90** [comment]
Fixed in #1102.
