### ISSUE TITLE
Wrong detection of localizable method in case of class

### ISSUE THREAD

**Issue by Mte90** [GlotPress/GlotPress-WP#895]
The example is: https://translate.wordpress.org/projects/wp-plugins/vikbooking/dev/it/default?filters%5Bterm%5D=keepalive&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

Code example: https://plugins.trac.wordpress.org/browser/vikbooking/trunk/admin/views/dashboard/tmpl/default.php#L82

Just for reference: ```JHTML::_('behavior.keepalive');```

The method is from a class so is not from gettext, we need a way to say to GlotPress to ignore this cases.

**Comment by ocean90** [comment]
GlotPress doesn't extract strings, it only gets its data from an import of one of the supported formats.

**Comment by toolstack** [comment]
That's a bug in the makepot code, which is part of meta-i18n/wp core, probably opening a ticket over there would get the right people looking at the code.

**Comment by Mte90** [comment]
The plugin author say that they never imported anything but automatically glotpress found this strings and they tried to remove it with a manual import with the only right string but glotpress not removed them.

**Comment by toolstack** [comment]
You can't update originals to translate.w.org so there's no way for a user to remove strings.

It's the automated extraction that needs to be fixed on translate.w.org.  As makepot is designed to run against PHP files, the most likely solution would be to ignore javascript files during the extraction.

**Comment by Mte90** [comment]
That code that generated this wrong strings is PHP.
I will open a ticket to meta for https://i18n.svn.wordpress.org/tools/trunk/makepot.php

**Comment by Mte90** [comment]
Opened https://meta.trac.wordpress.org/ticket/3601#ticket
