### ISSUE TITLE
Allow access without trailing slash for site-url/glotpress

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#896]
Hello,

I just installed the plugin and was trying to access Glotpress and got a 404 until I added the trailing slash.

So this url - http://glotpress.eclipsedev.tk/glotpress
Loads the WP 404

But if I supply the trailing slash - http://glotpress.eclipsedev.tk/glotpress/
Then it redirects to - http://glotpress.eclipsedev.tk/glotpress/projects/

Can the redirect logic be updated to function when no tailing slash is there.

Thanks

**Comment by toolstack** [comment]
It could, but we follow whatever the user has configured for WordPress in the permalinks.

So if your permalink setting ends in a trailing slash we require GP to as well.  If it doesn't, GP doesn't require one either.

That way we keep consistent with other content on the site.

**Comment by garretthyder** [comment]
Thanks @toolstack that makes sense. 
Looking at WP it seems to redirect automatically to append the slash for you if it's a valid page.
So http://glotpress.eclipsedev.tk/sample-page will redirect to http://glotpress.eclipsedev.tk/sample-page/
So should we follow that approach to avoid the 404?

**Comment by toolstack** [comment]
It's possible, I would see that more as a plugin at the moment as we don't get too many complaints about it in general.

**Comment by garretthyder** [comment]
No worries, thank you

**Comment by ocean90** [comment]
Reopening. We should follow WordPress here and do a canonical redirect to improve the initial experience since appending `glotpress` is currently the only way to get to the GlotPress pages,  see #259.
