### ISSUE TITLE
New Bulk Actions in footer shouldn't appear for logged out users

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#901]
Original Trac Ticket - https://meta.trac.wordpress.org/ticket/3618

> Thank you for adding the Bulk Actions to the footer of translate.wordpress.org, just wanted to point out they should follow the same conditional logic as the Bulk Actions found above the table. And by that I mean when you're not logged in they shouldn't be present as you can't select any rows to conduct the bulk actions on. Please just follow the conditions for injecting as donw for the Bulk Actions above the table.
> This is for translate.wordpress.org see screenshot.
![screen shot 2018-05-11 at 4 05 11 pm](https://user-images.githubusercontent.com/8726005/40011832-d640cf02-575d-11e8-8d92-567a724bfe74.png)

Quoting @ocean90 
> The bulk actions are part of GlotPress and the toolbar in the footer was added in https://github.com/GlotPress/GlotPress-WP/pull/797.

**Comment by toolstack** [comment]
The bottom bulk action bar is missing the check for 'can_approve' which causes this.

**Comment by garretthyder** [comment]
Thanks @toolstack
