### ISSUE TITLE
iOS .strings file incorrectly assumes UTF16-LE encoding

### ISSUE THREAD

**Issue by LucaFagan** [GlotPress/GlotPress-WP#903]
I've installed the plugin, created the project and then imported a .strings file.

Translation list is empty.

Someone can help me to solve this problem ?

**Comment by toolstack** [comment]
Did you import the originals or just a translation set?

**Comment by LucaFagan** [comment]
The originals, i.e. source strings that I want to translate in other languages.
The list of strings to translate is empty.

**Comment by toolstack** [comment]
Yes, but have you imported the originals in to the project, aka Project->Project actions->Import Originals?

After that you have to create a translation set for each language you want to translate to, Project->Project actions->New Translation Set.

**Comment by LucaFagan** [comment]
I've done those things but in the list there are no strings to translate. 

<img width="775" alt="schermata 2018-05-16 alle 21 34 07" src="https://user-images.githubusercontent.com/7376037/40139772-4a7b36ba-5951-11e8-994c-89d08dea080e.png">

It seems the "import originals" does not work, the table wp_gp_originals is empty. 

<img width="945" alt="schermata 2018-05-16 alle 21 34 24" src="https://user-images.githubusercontent.com/7376037/40139806-5ccd7fda-5951-11e8-9538-f8ae34f451d5.png">


The file I've tried to import is localizable.strings and contains:

"STR_Success" = "Success!";
"STR_Error" = "Error!";
"STR_Warning" = "Warning!";
"STR_Attention" = "Attention!";
"STR_Wait" = "Please wait!";
"STR_Saving" = "Saving...";
"STR_Menu_Item_Gateways" = "Gateways";
"STR_Menu_Item_Broadcast" = "Broadcast";
"STR_Menu_Item_Favourites" = "Favourites";
"STR_Menu_Item_Configuration" = "Configuration";
"STR_Menu_Item_AddGateway" = "Add gateway";
"STR_Menu_Item_SetGatewayIds" = "Set gateway IDs";
"STR_Menu_Item_Settings" = "Settings";
"STR_Menu_Item_GroupNames" = "Group names";
"STR_Menu_Item_SceneNames" = "Scene names";
"STR_Menu_Item_Network" = "Network";
"STR_Menu_Item_Login" = "Login";
"STR_Login_Caption" = "EyeWiFi Login";
"STR_Login_Error" = "Wrong username or password!";
"STR_Login_Button_Login" = "Login";
"STR_Login_Button_Logout" = "Logout";


I'm trying in my mac using the following configuration:
1) MAMP 4.4.1
2) PHP 7.2.1
3) Wordpress 4.9.5

**Comment by toolstack** [comment]
Can you check to make sure your string file is UTF16-LE encoded before you import it?

**Comment by LucaFagan** [comment]
It's a normal txt file.

If you want to try, here is the file:

[localizable.strings](https://drive.google.com/file/d/1vMC1A1lpTyisuUNx-OENUFp5p0YruxbW/view?usp=sharing)

**Comment by toolstack** [comment]
That's the problem, not sure why but the .strings format assumes the file is in UTF16-LE format and then converts it to UTF8.  If it's already in UTF8 it will garble the file and no strings will be imported.

This seems to be a hold over from the standalone code and not the [current recommendation](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html) from Apple.

I'm going to mark this as a bug and will create a PR for it, but in the mean time save the file as UTF16-LE  and then it should import correctly.

**Comment by LucaFagan** [comment]
Thanks, converting the file works.

Waiting for the PR.

Regards

**Comment by toolstack** [comment]
We'll just leave the issue open and let the PR close it automatically so we can keep track of it.

**Comment by toolstack** [comment]
I reached out to the WP mobile folks on Slack to get some feedback on UTF8 vs UTF16LE and updated the PR to continue to support UTF16LE for imports (UTF8 is also now supported) as some of the Apple tools output it by default.

https://wordpress.slack.com/archives/C02RQC4LY/p1526569592000356
