### ISSUE TITLE
Multiplatform translator

### ISSUE THREAD

**Issue by LucaFagan** [GlotPress/GlotPress-WP#906]
Hi, 
I've just discovered this useful plugin and tested it with an iOS app.

Is it possible to manage multiplatform? I mean:
- create a project for an iOS app
- translate strings in the iOS project
- create a second project or subproject for Android app
- auto-translate automatically strings in the Android project taking translatrion from the iOS one.

**Comment by toolstack** [comment]
Yes, you can create projects for as many different projects as you have and export them to the desired formats.

You can't "auto translate" between projects but you could export from one and import to the other assuming they had (mostly) the same originals.

**Comment by LucaFagan** [comment]
When you say "the same originals" do you mean the 2 projects must have the same string IDs ?

**Comment by toolstack** [comment]
Yes, for the translations to import correctly they have to be able to match between the two projects.

In general, this kind of import/export is frowned upon as it tends to be error prone.  Once the projects are setup in GP, it easier just to do the translation in both projects as you would have some unique strings to each project anyway.

**Comment by LucaFagan** [comment]
Ok, thanks

**Comment by ocean90** [comment]
You can take a look at https://github.com/GlotPress/gp-translation-propagation. It copies translations to other projects if the original string matches.

**Comment by LucaFagan** [comment]
Very good! I'll try it.

**Comment by LucaFagan** [comment]
Installed right now but I don't understand how to use it.
