### ISSUE TITLE
'Copy from original' broken on Rejected row

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#908]
Hello,

Came across an issue with recently Rejected rows and the 'Copy from original' action.

When you reject a row, reopen it and click 'Copy from original' the page goes to the top and an error appears in JS console;
> Uncaught TypeError: Cannot read property 'split' of undefined
>     at Object.copy (editor.min.js:1)
>     at HTMLAnchorElement.copy (editor.min.js:1)
>     at HTMLTableElement.dispatch (jquery.js:3)
>     at HTMLTableElement.r.handle (jquery.js:3)

Cracking open the file it's for this line in the copy action;
var e = d.parents(".textareas").find("textarea").attr("id").split("_");

Inspecting I tried to follow the path and all the elements and attributes in the selectors are present and set so not sure why it's kicking the error. 

And I just checked but it seems this happens with both the Fuzzy and Reject actions. If you reload then it's no issue so it's only right after conducting the action that the problem occurs. It almost reminds me of issues for ajax/dynamic content and click actions and needing the .on click action instead.

Hope that makes sense

Cheers

**Comment by toolstack** [comment]
I don't seem to be able to reproduce the issue, could you provide a few more details:

- Browser Version
- GP Version
- Standalone or on translate.w.org?

**Comment by garretthyder** [comment]
Thanks @toolstack 
You're right I disable GlotDict and the issue goes away so I've opened a clone of this over on GlotDict here;
https://github.com/Mte90/GlotDict/issues/148
