### ISSUE TITLE
Android Strings: Escaped Unicode is imported mangled

### ISSUE THREAD

**Issue by akirk** [GlotPress/GlotPress-WP#910]
When an Android strings file contains an entry like this:
```
<string name="reader_empty_saved_posts_title">No posts saved \u2014 yet!</string>
```

the import of this creates a mangled original with the text `No posts saved u2014 yet!`. As we can assume that translators can display UTD-8, it should actually be `No posts saved — yet!`.

**Comment by maxme** [comment]
The same issue happened again recently. I don't know if this is the same problem though, but the symptoms are similar:

The strings [here](https://github.com/wordpress-mobile/WordPress-Android/blob/616a6341e8b358298af175eec113de7219501f77/WordPress/src/main/res/values/strings.xml#L371-L372) got incorrectly imported [there](dialog_gutenberg_informative_description) (same unicode problem `u2014`).
