### ISSUE TITLE
Multiple Identical Terms get stacked in Glossary tooltip

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#915]
Hello,

Came across a minor doubling up that occurs in the Glossary Tooltips if there's multiple identical terms in the string.
Screenshot; 
![screen shot 2018-07-03 at 12 13 59 pm](https://user-images.githubusercontent.com/8726005/42240147-35e86396-7ebb-11e8-8097-d1ff7e8a423f.png)

Example - https://translate.wordpress.org/projects/wp-plugins/poptin/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4944988&filters%5Btranslation_id%5D=56024273

Cheers

**Comment by toolstack** [comment]
That's mostly on purpose as you can have different glossary entries for the same term (aka noun, verb, etc.).

We don't do any double checking for duplicates of the same type/identical descriptors though.

**Comment by garretthyder** [comment]
Hi @toolstack, sorry I should clarify to remove any confusion here.

The issue isn't that there's two entries of 'program' in the en_CA Glossary, but rather that when the term exists within the source string twice or more then each instance in the source string will have a tooltip containing multiple entries of the term info, one per instance of the term.

So if we compare two entries that contain the same term but one has multiple instance we can see the duplication in the tooltip.

Single Term (Single Entry) - https://translate.wordpress.org/projects/wp-plugins/poptin/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4944496&filters%5Btranslation_id%5D=56068436
Screenshot - 
![screen shot 2018-07-03 at 1 49 34 pm](https://user-images.githubusercontent.com/8726005/42243983-fa9b1cb8-7ec7-11e8-87af-610dbf3c0d06.png)


Multiple Terms (Multiple Entries) - https://translate.wordpress.org/projects/wp-plugins/poptin/dev-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4944988&filters%5Btranslation_id%5D=56068432
Screen - 
![screen shot 2018-07-03 at 11 15 43 am](https://user-images.githubusercontent.com/8726005/42243958-e50d4a10-7ec7-11e8-92a1-e9fa8ad6ba74.png)


As you can see in the examples they both use 'program' as the term and when it's the only instance in the string only one entry appears in the tooltip, but when there's more than one instance of the term in the string then the tooltips for each instance have multiple entries.

Hopefully that makes a bit more sense.

**Comment by toolstack** [comment]
Ah, yes, that makes more sense, definitely a bug then ;)

**Comment by garretthyder** [comment]
Awesome thanks for the PR @toolstack
