### ISSUE TITLE
Glossary UI Improvements - Spacing & Overlap

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#916]
Hello,

I just wanted to suggest two minor improvements to the Glossary UI.
![screen shot 2018-07-03 at 1 57 32 pm](https://user-images.githubusercontent.com/8726005/42244296-599eb156-7ec9-11e8-8e95-da522ffab49f.png)

1. All the fields and buttons seem quite tight and could use some padding.
2. The Meta box overlaps the Comments field.

All the best,
Cheers

**Comment by toolstack** [comment]
I can't reproduce the overlap issue, which browser and GP version are you running?

**Comment by garretthyder** [comment]
Hi @toolstack 

Not sure how to determine GP version of translate.wp.org but that's where I'm seeing the overlap;
https://translate.wordpress.org/locale/en-ca/default/glossary

As to browser I just checked Chrome, Opera, FF and Safari and they all have the same issue. Version info;
Chrome - Version 67.0.3396.99 (Official Build) (64-bit)
Opera - 53.0.2907.99
FF Quantum - 61.0 (64-bit) 
Safari - Version 10.1.2 (10603.3.8)fi

Hope that helps,
Cheers

**Comment by toolstack** [comment]
The overlap issue is probably a bug in the GP theme that translate.w.org uses, probably need to open a Trac ticket for that.

**Comment by garretthyder** [comment]
Thanks @toolstack I've moved this to Meta Trac here;
https://meta.trac.wordpress.org/ticket/3697#ticket
