### ISSUE TITLE
Comments from reviewing or rejecting a Translation

### ISSUE THREAD

**Issue by davidperezgar** [GlotPress/GlotPress-WP#920]
Hello, in our community in Spain, I've detected that when a user translated strings in wordpress.org, we cannot send messages or comments about the translation to the user, in order to teach how to translate correctly. 

So in Glotpress, there is no way to send to the translator that the translation was rejected or changed due a reason. Even, the reasons could be a list that the administrators could make and moderate.

The user won't learn and the system can't improve due of communication. The only way to speak with the user is in Slack, but I think that is not the efficient way, and a lot of users haven't got an account.

And the User should get a notification about the translations approved, reasons of rejected or changed, to better understand how are the rules of translation team.

**Comment by Presskopp** [comment]
see #324, #323, #804

**Comment by toolstack** [comment]
Closing as duplicate.
