### ISSUE TITLE
Provide count when filtering

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#925]
A request was originally made on GlotDict to provide a count of the strings returned when filtering;
https://github.com/Mte90/GlotDict/issues/179#issuecomment-419765363

I looked into this for GlotDict but when the results are paginated the information isn't available to javascript without unnecessary requests.

It would be nice to have a notice appear when the filter is run with the results count similar to the notices you receive when importing or bulk submitting;
<img width="284" alt="screen shot 2018-09-20 at 12 57 06 am" src="https://user-images.githubusercontent.com/8726005/45804236-657f4a00-bc70-11e8-9f32-b8dbea4929b0.png">
<img width="229" alt="screen shot 2018-09-20 at 12 59 01 am" src="https://user-images.githubusercontent.com/8726005/45804237-6617e080-bc70-11e8-99cb-296338c322bc.png">

Thanks

**Comment by toolstack** [comment]
How about we add a "Current Filter" count to the end of the standard count list when a filter is active.  Something like:

![current filter](https://user-images.githubusercontent.com/9053749/45823918-c765a100-bcbc-11e8-82ac-94078e05a1c4.png)

**Comment by garretthyder** [comment]
Thanks @toolstack 

That could suffice, although we might want to make it not look like a link or users could be confused and try clicking at it.

I posted a quick thought in Slack - https://wordpress.slack.com/archives/C02RP4R9F/p1537459419000100
> I was either thinking that could be a notice with the filter count. Or if the pagination is just updated to give numbers like 1-100 of 1000 that would probably also suffice and could be useful to all views not just filter views

Thanks

**Comment by toolstack** [comment]
It will be a link, and you can click on it ;)  

That way you can refresh the current filtered view.

The problem with ranges is that it makes the pagination control much larger, which isn't good on small displays.

**Comment by garretthyder** [comment]
That's a good point @toolstack I hadn't thought of a need to refresh but as you can affect strings in view to have them removed from the filter a refresh is a useful thing.
And I agree the count in pagination could be overbearing there.
Let's go with your initial proposal there, thanks for providing a use case for why making it a link is helpful

**Comment by khoipro** [comment]
+1 (like)
