### ISSUE TITLE
Duplicate strings with unique comments should be separate rows

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#930]
Hello,

When a string with multiple instances has a comment supplied that's unique for each instance those instances should all be unique rows instead of a merged instance as those comments can provide context which may lead to alternate translations.

Some examples;
https://translate.wordpress.org/projects/wp/dev/admin/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=2357863&filters%5Btranslation_id%5D=38532994
https://translate.wordpress.org/projects/wp/dev/admin/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=2357860&filters%5Btranslation_id%5D=38532991
https://translate.wordpress.org/projects/wp/dev/admin/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=2357859&filters%5Btranslation_id%5D=38532990
https://translate.wordpress.org/projects/wp/dev/admin/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=2357858&filters%5Btranslation_id%5D=38532989
https://translate.wordpress.org/projects/wp/dev/admin/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=2357857&filters%5Btranslation_id%5D=38532988
https://translate.wordpress.org/projects/wp/dev/admin/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=2357855&filters%5Btranslation_id%5D=38533010

In most of the above cases the comment is to indicate what a param is and in the above it's different in some cases as in one it's about the page while the other is the term, etc. 

Due to this would make sense that each would be a unique translation.

**Comment by toolstack** [comment]
They actually already are, they each have a newline at the end of them, they just haven't been html formatted ;)

**Comment by garretthyder** [comment]
Thanks @toolstack 
I was more meaning completely segregated translations rather than just the new lines.
But it sounds like that's more of a POT source issue than GP so to separate them into unique strings would be a string extractor issue so created a Meta ticket;
https://meta.trac.wordpress.org/ticket/3857
Feel free to add any additional thoughts.
