### ISSUE TITLE
Block to add strings that alread exist as rejected

### ISSUE THREAD

**Issue by Mte90** [GlotPress/GlotPress-WP#950]
A little bit of background:

- User A do a translation
- User B rejected it
- [pass a long of time]
- User C add a new translation that is the same of User A and got uploaded

This take to a lot of multiple localizations in the DB never used that are right and the original one that uploaded also if rejected can complain "why you reject mine and approved the other one?"
I think that this can help on keep cleaning the DB and when there will be some integrations with notification can improve the effect of UX on the portal.
SO my proposal in this case is better to add some alert or move the original one rejected as fuzzy as example.

**Comment by toolstack** [comment]
I'm not sure if this is a good idea, it may block strings that are valid, for example:

- User A does a Translation1 of Orig1
- User B rejects it
- User C add the correct Translation2 of Orig1
- User B accepts it
- New originals get imported and Orig1 gets updated, Trnslation2 is marked as fuzz
- Translation1 is now the correct translation but has rejected
- User C re-submits the same translation (Translation1) but is blocked as it is now identified as a duplicate

I don't think the overhead on the DB is so significant to necessitate this kind of blocking.

**Comment by Mte90** [comment]
Well, for me is better that if the right translation is already in the db use it instead add a new one. This happen often when there are changes with glossaries and people cleanup with legacy stuff.
Also this can automatize a little the process. Maybe we can find a better workflow like if you are a contributor there is an alert about existing string and we move that to fuzzy automatically so reviewer can check them.

**Comment by toolstack** [comment]
It's something to think about, for the time being I'm going to close this one as `maybelater` if we can come up with a compelling reason for it.
