### ISSUE TITLE
iOS Strings: support for UTF-8 string format

### ISSUE THREAD

**Issue by loremattei** [GlotPress/GlotPress-WP#957]
When strings files are imported into GlotPress, it assumes they're UTF-16LE encoded, but the recommended encoding is UTF-8, as per this doc: 
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html

Since UTF-8 seems to be the widely accepted and used standard, support for it in GlotPress import/export would be very useful.

**Comment by ocean90** [comment]
Support for UTF-8 was added in #903 via #905.
