### ISSUE TITLE
Idea: warning for locale-specific rules 

### ISSUE THREAD

**Issue by naokomc** [GlotPress/GlotPress-WP#961]
This is just an idea, but I've been mulling over this for a while so I thought I'd document it.

When I review translations of others (especially new contributors), I often find myself spending time correcting & telling about the same issues that are against the rules in [our style guide](https://wpdocs.osdn.jp/WordPress_の翻訳/翻訳スタイルガイド). 

Here are some examples:

**Warning** (if these are violated, the translation should never be approved)

1. Never use multibyte symbols and numbers such as: `１`,`？`,`！`,`％`,`＄`
2. Use hiragana instead of kanji for "全て" (= all), "下さい" (= please) 

**Notice** (there are some exceptions so the translator needs to confirm that it's not against the rule)

1. In most cases, try to omit the word "you (`あなた`)"
2. Place a single-byte space before & after an alphabetic word/phrase, unless it's right next to one of the following:` 。`,`、`,`:`,`(`,`)` etc... 

I'm sure there are similar types of (relatively) minor but style-violating mistakes that often come up for each locale. Correcting these are very mind-numbing for editors, but at the same time, it's not very easy for new contributors to understand all these rules in the first place.

I think it's best if GlotPress can automatically handle these kinds of warnings and notices so editors can spend more time on other things.

**Comment by toolstack** [comment]
This would be site specfic, for example the style guide mentioned is for translate.w.org, so not something we'd include in the coe GlotPress code base.

You might want to open a ticket on [trac](https://meta.trac.wordpress.org/query?status=!closed&component=Translate+Site+%26+Plugins) forit.

**Comment by naokomc** [comment]
Thanks for pointing me to the right place.

Edit: Now reported on https://meta.trac.wordpress.org/ticket/3891
