### ISSUE TITLE
Make it easier to extend templates

### ISSUE THREAD

**Issue by swissspidy** [GlotPress/GlotPress-WP#969]
Right now there's no easy way to edit templates like the project edit form (https://github.com/GlotPress/GlotPress-WP/blob/99d0799ab378d16eb0c5cb63be0fead7f06c201d/gp-templates/project-form.php) without completely overriding the templates on your site. 

An action hook in `project-form.php` to allow plugins to print additional settings fields would already be of great help.

**Comment by toolstack** [comment]
You'd also need a hook on the route to be able to do something with the added fields, as otherwise they would just be dropped when the project was saved to the database.

**Comment by 2ndkauboy** [comment]
As @swissspidy indicated, I had to overwrite the whole template. Saving the new fields, I have used two available actions like this:

```php
function gp_project_save_custom_field( $project, $projectBefore ) {
    $projectPostData = gp_post( 'project' );
    if ( isset( $projectPostData['custom_field'] ) ) {
        gp_update_meta( project->id, '_custom_field', $projectPostData['custom_field'], 'project' );
    }
}

add_filter( 'gp_project_saved', 'gp_project_save_custom_field', 10, 2 );
add_filter( 'gp_project_created', 'gp_project_save_custom_field', 10, 1 );
```

The action to add some additional fields would have helped a lot to avoid overwriting the whole template. At least with the `gp_tmpl_load_locations` it was fortunately possible to add such a template, but only using `array_unshift` to move the custom directory to the front of the list.
