### ISSUE TITLE
Add local date display to editor

### ISSUE THREAD

**Issue by toolstack** [GlotPress/GlotPress-WP#972]
Currently in meta we display the date a translation was added to GP in GMT, which is fine but we should also display it in the local time as well to make it easy for the user.

Something like this:

![meta](https://user-images.githubusercontent.com/9053749/48434758-a6637e80-e748-11e8-925e-a88542a07b29.png)

**Comment by ocean90** [comment]
Why does it need to be a second row instead of showing the local date by default? See https://make.wordpress.org/meetings/ for an example.

**Comment by Mte90** [comment]
Well in that way we are adding a link to an external website to see the time (or require mouse hover but is not easy to discover).
So in the pr proposal we have the time on gmt and based on the timezone of how visit without any other interaction, more fast and simple. Also is not blocking the UX because you have everything in the page.

**Comment by toolstack** [comment]
@ocean90 it doesn't need to be on a second row, but it seemed like the best way to provide both to make it easy for the user to decide which one they wanted.

As @mte90 mentioned, using a title/mouseover event to provide the original data is hard to discover and on non-mouse devices doesn't work most of the time.

I did consider doing something like:

```Date Added (GMT/Local): 2017-09-05 14:26:17 / 2017-09-05 9:26:17 a.m```

But that seemed like it would be too long (especially with the notes adding a third column) and would create word wrap nightmares :wink:

**Comment by ocean90** [comment]
I'm assuming you are talking about title/mouseover because you want to see the UTC time as well? Not sure if that's actually needed. Just show the local time...

**Comment by toolstack** [comment]
I didn't want to assume one way or the other quite honestly, if people are use to GMT and want to continue to use it I don't see a reason to remove it.

**Comment by Mte90** [comment]
![immagine](https://user-images.githubusercontent.com/403283/48486131-eb57e580-e81a-11e8-8cff-1867af05d2f0.png)
In that page I see in that way but is not clear a lot for who doesn't know that CET is like GMT and doesn't know that there is a timezone problem with the meeting. 
Not everyone think that the message is written in the same time but is converted for timezones.
For us more techie is quite clear but for localizers is not clear often.

**Comment by toolstack** [comment]
Leaving the GMT time displayed also helps with collaboration as if two translators in different timezones are looking at the same string and chatting, they can both verify the timestamp via the GMT value.
