### ISSUE TITLE
Multi-check functionality only works forward and not backwards

### ISSUE THREAD

**Issue by garretthyder** [GlotPress/GlotPress-WP#979]
Hello,

The multi-select function of checkboxes only works going down the page and not back up. By the multi-select function I speak on when you check a checkbox and then skip a few rows and check another checkbox then all checkboxes in between become checked. The code for this;
https://github.com/GlotPress/GlotPress-WP/blob/43bb5383e114835b09fc47c727d06e6d3ca8114e/assets/js/translations-page.js#L47-L68

This only works from top to bottom, it would be nice if it worked in reverse as well so if you check a box low in the page and then go up and check another then all boxes in between get checked.

How it functions going down the page;
![Multi-Check Downwards](https://i.gyazo.com/7abe84a80f5b9ef80243b6c3a4541d8f.gif)

Going in reverse this illustrates how it doesn't check the boxes in between;
![Failed Multi-Check Upwards](https://i.gyazo.com/5b1b54799c8d1ace5a0d395b74fe8f55.gif)

Hope that makes sense,
Cheers

**Comment by toolstack** [comment]
Seems like an easy fix, just add the following after first/last are calculated:
```
if( first > last ) { swap = last; last = first; first = swap; }
```

Of course there is the note above that the code was taken from WP, so perhaps it's already been fixed there?

**Comment by toolstack** [comment]
Just took a look, they have fixed it in WP:
```
			if ( 0 < first && 0 < last && first != last ) {
				sliced = ( last > first ) ? checks.slice( first, last ) : checks.slice( last, first );
				sliced.prop( 'checked', function() {
					if ( $(this).closest('tr').is(':visible') )
						return checked;

					return false;
				});
			}
```
